var Layer_24088287_091098_59_02 = {
"type": "FeatureCollection",
"features": [
{ "type": "Feature", "properties": { "ID": "1", "SOATO_U": "0120100001", "UkrName": "Андріївка", "RusName": "Андреевка", "EngName": "Andriivka", "EngName_Tr": "Andriivka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.093390, 51.129550 ] } }
,
{ "type": "Feature", "properties": { "ID": "2", "SOATO_U": "0120100002", "UkrName": "Бенівка", "RusName": "Беневка", "EngName": "Benivka", "EngName_Tr": "Benivka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.975270, 51.446920 ] } }
,
{ "type": "Feature", "properties": { "ID": "3", "SOATO_U": "0120100003", "UkrName": "Бички", "RusName": "Бычки", "EngName": "Bychky", "EngName_Tr": "Bychky", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.867690, 51.206410 ] } }
,
{ "type": "Feature", "properties": { "ID": "4", "SOATO_U": "0120100004", "UkrName": "Буда", "RusName": "Буда", "EngName": "Buda", "EngName_Tr": "Buda", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.770210, 51.392680 ] } }
,
{ "type": "Feature", "properties": { "ID": "5", "SOATO_U": "0120100005", "UkrName": "Буряківка", "RusName": "Буряковка", "EngName": "Buriakivka", "EngName_Tr": "Buriakivka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.916410, 51.380820 ] } }
,
{ "type": "Feature", "properties": { "ID": "6", "SOATO_U": "0120100006", "UkrName": "Глинка", "RusName": "Глинка", "EngName": "Hlynka", "EngName_Tr": "Hlynka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.910860, 51.235420 ] } }
,
{ "type": "Feature", "properties": { "ID": "7", "SOATO_U": "0120100007", "UkrName": "Городище", "RusName": "Городище", "EngName": "Horodyshche", "EngName_Tr": "Horodyshche", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.393060, 51.138070 ] } }
,
{ "type": "Feature", "properties": { "ID": "8", "SOATO_U": "0120100008", "UkrName": "Городчан", "RusName": "Городчан", "EngName": "Horodchan", "EngName_Tr": "Horodchan", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.288010, 51.455430 ] } }
,
{ "type": "Feature", "properties": { "ID": "9", "SOATO_U": "0120100009", "UkrName": "Залісся", "RusName": "Залесье", "EngName": "Zalissia", "EngName_Tr": "Zalissia", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.188860, 51.255190 ] } }
,
{ "type": "Feature", "properties": { "ID": "10", "SOATO_U": "0120100010", "UkrName": "Замошня", "RusName": "Замошня", "EngName": "Zamoshnia", "EngName_Tr": "Zamoshnia", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.895140, 51.233820 ] } }
,
{ "type": "Feature", "properties": { "ID": "11", "SOATO_U": "0120100011", "UkrName": "Запілля", "RusName": "Заполье", "EngName": "Zapillia", "EngName_Tr": "Zapillia", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.126700, 51.256020 ] } }
,
{ "type": "Feature", "properties": { "ID": "12", "SOATO_U": "0120100012", "UkrName": "Зимовище", "RusName": "Зимовише", "EngName": "Zymovyshche", "EngName_Tr": "Zymovyshche", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.176080, 51.420140 ] } }
,
{ "type": "Feature", "properties": { "ID": "13", "SOATO_U": "0120100013", "UkrName": "Іванівка", "RusName": "Ивановка", "EngName": "Ivanivka", "EngName_Tr": "Ivanivka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.252060, 51.245050 ] } }
,
{ "type": "Feature", "properties": { "ID": "14", "SOATO_U": "0120100014", "UkrName": "Іллінці", "RusName": "Ильинцы", "EngName": "Illintsi", "EngName_Tr": "Illintsi", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.853670, 51.296650 ] } }
,
{ "type": "Feature", "properties": { "ID": "15", "SOATO_U": "0120100015", "UkrName": "Іловниця", "RusName": "Иловница", "EngName": "Ilovnytsia", "EngName_Tr": "Ilovnytsia", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.067700, 51.180220 ] } }
,
{ "type": "Feature", "properties": { "ID": "16", "SOATO_U": "0120100016", "UkrName": "Кам'янка", "RusName": "Каменка", "EngName": "Kam'yanka", "EngName_Tr": "Kam'yanka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.250200, 51.174610 ] } }
,
{ "type": "Feature", "properties": { "ID": "17", "SOATO_U": "0120100017", "UkrName": "Копачі", "RusName": "Копачи", "EngName": "Kopachi", "EngName_Tr": "Kopachi", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.128120, 51.350640 ] } }
,
{ "type": "Feature", "properties": { "ID": "18", "SOATO_U": "0120100018", "UkrName": "Корогод", "RusName": "Корогод", "EngName": "Korohod", "EngName_Tr": "Korohod", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.021050, 51.275580 ] } }
,
{ "type": "Feature", "properties": { "ID": "19", "SOATO_U": "0120100019", "UkrName": "Коцюбинське", "RusName": "Коцюбинське", "EngName": "Kotsiubyns'ke", "EngName_Tr": "Kotsiubyns'ke", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.246500, 51.457430 ] } }
,
{ "type": "Feature", "properties": { "ID": "20", "SOATO_U": "0120100020", "UkrName": "Кошарівка", "RusName": "Кошаровка", "EngName": "Kosharivka", "EngName_Tr": "Kosharivka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.007090, 51.427340 ] } }
,
{ "type": "Feature", "properties": { "ID": "21", "SOATO_U": "0120100021", "UkrName": "Кошівка", "RusName": "Кошевка", "EngName": "Koshivka", "EngName_Tr": "Koshivka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.241270, 51.319970 ] } }
,
{ "type": "Feature", "properties": { "ID": "22", "SOATO_U": "0120100022", "UkrName": "Красне (Машівська с\/р )", "RusName": "Красное (Машівська с\/р )", "EngName": "Krasne (Mashivs'ka s\/r )", "EngName_Tr": "Krasne (Mashivs'ka s\/r )", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.119650, 51.456160 ] } }
,
{ "type": "Feature", "properties": { "ID": "23", "SOATO_U": "0120100023", "UkrName": "Красне (Товстоліська с\/р )", "RusName": "Красное (Товстоліська с\/р )", "EngName": "Krasne (Tovstolis'ka s\/r )", "EngName_Tr": "Krasne (Tovstolis'ka s\/r )", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.750640, 51.400370 ] } }
,
{ "type": "Feature", "properties": { "ID": "24", "SOATO_U": "0120100024", "UkrName": "Крива Гора", "RusName": "Кривая Гора", "EngName": "Kryva Hora", "EngName_Tr": "Kryva Hora", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.206240, 51.381590 ] } }
,
{ "type": "Feature", "properties": { "ID": "25", "SOATO_U": "0120100025", "UkrName": "Купувате", "RusName": "Куповатое", "EngName": "Kupuvate", "EngName_Tr": "Kupuvate", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.369730, 51.155580 ] } }
,
{ "type": "Feature", "properties": { "ID": "26", "SOATO_U": "0120100026", "UkrName": "Ладижичі", "RusName": "Ладыжичи", "EngName": "Ladyzhychi", "EngName_Tr": "Ladyzhychi", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.413500, 51.251650 ] } }
,
{ "type": "Feature", "properties": { "ID": "27", "SOATO_U": "0120100027", "UkrName": "Лелів", "RusName": "Лелев", "EngName": "Leliv", "EngName_Tr": "Leliv", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.188410, 51.311150 ] } }
,
{ "type": "Feature", "properties": { "ID": "28", "SOATO_U": "0120100028", "UkrName": "Машеве", "RusName": "Машеве", "EngName": "Masheve", "EngName_Tr": "Masheve", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.146360, 51.487350 ] } }
,
{ "type": "Feature", "properties": { "ID": "29", "SOATO_U": "0120100029", "UkrName": "Нова Красниця", "RusName": "Новая Красница", "EngName": "Nova Krasnytsia", "EngName_Tr": "Nova Krasnytsia", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.836810, 51.394680 ] } }
,
{ "type": "Feature", "properties": { "ID": "30", "SOATO_U": "0120100030", "UkrName": "Новосілки", "RusName": "Новоселки", "EngName": "Novosilky", "EngName_Tr": "Novosilky", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.063150, 51.217950 ] } }
,
{ "type": "Feature", "properties": { "ID": "31", "SOATO_U": "0120100031", "UkrName": "Новошепеличі", "RusName": "Новошепеличи", "EngName": "Novoshepelychi", "EngName_Tr": "Novoshepelychi", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.024430, 51.420540 ] } }
,
{ "type": "Feature", "properties": { "ID": "32", "SOATO_U": "0120100032", "UkrName": "Опачичі", "RusName": "Опачичи", "EngName": "Opachychi", "EngName_Tr": "Opachychi", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.325100, 51.202080 ] } }
,
{ "type": "Feature", "properties": { "ID": "33", "SOATO_U": "0120100033", "UkrName": "Оташів", "RusName": "Оташев", "EngName": "Otashiv", "EngName_Tr": "Otashiv", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.388790, 51.201450 ] } }
,
{ "type": "Feature", "properties": { "ID": "34", "SOATO_U": "0120100034", "UkrName": "Паришів", "RusName": "Парышев", "EngName": "Paryshiv", "EngName_Tr": "Paryshiv", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.321640, 51.283580 ] } }
,
{ "type": "Feature", "properties": { "ID": "35", "SOATO_U": "0120100035", "UkrName": "Плютовище", "RusName": "Плютовище", "EngName": "Pliutovyshche", "EngName_Tr": "Pliutovyshche", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.305170, 51.216220 ] } }
,
{ "type": "Feature", "properties": { "ID": "36", "SOATO_U": "0120100036", "UkrName": "Прип'ять", "RusName": "Припять", "EngName": "Pryp'yat'", "EngName_Tr": "Pryp'yat'", "SettlType": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "м.Прип'ять (міськрада)", "DistrictR": "г.Припять (горсовет)", "DistrictE": "m. Pryp'yat' (mis'krada)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.070250, 51.377930 ] } }
,
{ "type": "Feature", "properties": { "ID": "37", "SOATO_U": "0120100037", "UkrName": "Річиця", "RusName": "Речица", "EngName": "Richytsia", "EngName_Tr": "Richytsia", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.845020, 51.418030 ] } }
,
{ "type": "Feature", "properties": { "ID": "38", "SOATO_U": "0120100038", "UkrName": "Роз'їждже", "RusName": "Разъезжее", "EngName": "Roz'izhdzhe", "EngName_Tr": "Roz'izhdzhe", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.901620, 51.282260 ] } }
,
{ "type": "Feature", "properties": { "ID": "39", "SOATO_U": "0120100039", "UkrName": "Розсоха", "RusName": "Россоха", "EngName": "Rozsokha", "EngName_Tr": "Rozsokha", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.970210, 51.167790 ] } }
,
{ "type": "Feature", "properties": { "ID": "40", "SOATO_U": "0120100040", "UkrName": "Рудня-Вересня", "RusName": "Рудня-Вересня", "EngName": "Rudnia-Veresnia", "EngName_Tr": "Rudnia-Veresnia", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.108670, 51.186990 ] } }
,
{ "type": "Feature", "properties": { "ID": "41", "SOATO_U": "0120100041", "UkrName": "Рудня-Іллінецька", "RusName": "Рудня Ильинецкая", "EngName": "Rudnia-Illinets'ka", "EngName_Tr": "Rudnia-Illinets'ka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.814270, 51.282700 ] } }
,
{ "type": "Feature", "properties": { "ID": "42", "SOATO_U": "0120100042", "UkrName": "Рудьки", "RusName": "Рудьки", "EngName": "Rud'ky", "EngName_Tr": "Rud'ky", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.796110, 51.420400 ] } }
,
{ "type": "Feature", "properties": { "ID": "43", "SOATO_U": "0120100043", "UkrName": "Стара Красниця", "RusName": "Старая Красница", "EngName": "Stara Krasnytsia", "EngName_Tr": "Stara Krasnytsia", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.845020, 51.344370 ] } }
,
{ "type": "Feature", "properties": { "ID": "44", "SOATO_U": "0120100044", "UkrName": "Старі Шепеличі", "RusName": "Старые Шепеличи", "EngName": "Stari Shepelychi", "EngName_Tr": "Stari Shepelychi", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.940500, 51.420290 ] } }
,
{ "type": "Feature", "properties": { "ID": "45", "SOATO_U": "0120100045", "UkrName": "Старосілля", "RusName": "Строселье", "EngName": "Starosillia", "EngName_Tr": "Starosillia", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.209940, 51.349760 ] } }
,
{ "type": "Feature", "properties": { "ID": "46", "SOATO_U": "0120100046", "UkrName": "Стечанка", "RusName": "Стечанка", "EngName": "Stechanka", "EngName_Tr": "Stechanka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.922770, 51.301680 ] } }
,
{ "type": "Feature", "properties": { "ID": "47", "SOATO_U": "0120100047", "UkrName": "Теремці", "RusName": "Теремцы", "EngName": "Teremtsi", "EngName_Tr": "Teremtsi", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.502980, 51.228660 ] } }
,
{ "type": "Feature", "properties": { "ID": "48", "SOATO_U": "0120100048", "UkrName": "Терехів", "RusName": "Терехов", "EngName": "Terekhiv", "EngName_Tr": "Terekhiv", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.052270, 51.133050 ] } }
,
{ "type": "Feature", "properties": { "ID": "49", "SOATO_U": "0120100049", "UkrName": "Товстий Ліс", "RusName": "Толстый Лес", "EngName": "Tovstyi Lis", "EngName_Tr": "Tovstyi Lis", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.800300, 51.386470 ] } }
,
{ "type": "Feature", "properties": { "ID": "50", "SOATO_U": "0120100050", "UkrName": "Усів", "RusName": "Усов", "EngName": "Usiv", "EngName_Tr": "Usiv", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.043290, 51.472500 ] } }
,
{ "type": "Feature", "properties": { "ID": "51", "SOATO_U": "0120100051", "UkrName": "Хутір Золотніїв", "RusName": "Хутір Золотніїв", "EngName": "Khutir Zolotniiv", "EngName_Tr": "Khutir Zolotniiv", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.447190, 51.299700 ] } }
,
{ "type": "Feature", "properties": { "ID": "52", "SOATO_U": "0120100052", "UkrName": "Чапаївка", "RusName": "Чапаевка", "EngName": "Chapaivka", "EngName_Tr": "Chapaivka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.325410, 51.421860 ] } }
,
{ "type": "Feature", "properties": { "ID": "53", "SOATO_U": "0120100053", "UkrName": "Черевач", "RusName": "Черевач", "EngName": "Cherevach", "EngName_Tr": "Cherevach", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.148380, 51.216650 ] } }
,
{ "type": "Feature", "properties": { "ID": "54", "SOATO_U": "0120100054", "UkrName": "Чистогалівка", "RusName": "Чистогаловка", "EngName": "Chystohalivka", "EngName_Tr": "Chystohalivka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.018840, 51.354620 ] } }
,
{ "type": "Feature", "properties": { "ID": "55", "SOATO_U": "0120100055", "UkrName": "Чорнобиль", "RusName": "Чернобыль", "EngName": "Chornobyl'", "EngName_Tr": "Chornobyl'", "SettlType": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Іванківський", "DistrictR": "Иванковский", "DistrictE": "Ivankivs'kyi", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.225790, 51.267240 ] } }
,
{ "type": "Feature", "properties": { "ID": "56", "SOATO_U": "0120100057", "UkrName": "Ямпіль", "RusName": "Ямполь", "EngName": "Yampil'", "EngName_Tr": "Yampil'", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.178950, 51.203810 ] } }
,
{ "type": "Feature", "properties": { "ID": "57", "SOATO_U": "0120100058", "UkrName": "Янів", "RusName": "Янов", "EngName": "Yaniv", "EngName_Tr": "Yaniv", "SettlType": "селище", "SettlTypeR": "поселок", "SettlTypeE": "s. village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.058570, 51.388800 ] } }
,
{ "type": "Feature", "properties": { "ID": "58", "SOATO_U": "0123500001", "UkrName": "Бобер", "RusName": "Бобер", "EngName": "Bober", "EngName_Tr": "Bober", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Полісський (відселений)", "DistrictR": "Полесский (отселенный)", "DistrictE": "Poliss'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.548180, 51.157360 ] } }
,
{ "type": "Feature", "properties": { "ID": "59", "SOATO_U": "0123500002", "UkrName": "Бовище", "RusName": "Бовище", "EngName": "Bovyshche", "EngName_Tr": "Bovyshche", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Полісський (відселений)", "DistrictR": "Полесский (отселенный)", "DistrictE": "Poliss'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.760110, 51.343040 ] } }
,
{ "type": "Feature", "properties": { "ID": "60", "SOATO_U": "0123500003", "UkrName": "Варовичі", "RusName": "Варовичі", "EngName": "Varovychi", "EngName_Tr": "Varovychi", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Полісський (відселений)", "DistrictR": "Полесский (отселенный)", "DistrictE": "Poliss'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.548050, 51.290350 ] } }
,
{ "type": "Feature", "properties": { "ID": "61", "SOATO_U": "0123500004", "UkrName": "Весняне", "RusName": "Весняное", "EngName": "Vesniane", "EngName_Tr": "Vesniane", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Полісський (відселений)", "DistrictR": "Полесский (отселенный)", "DistrictE": "Poliss'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.651060, 51.311020 ] } }
,
{ "type": "Feature", "properties": { "ID": "62", "SOATO_U": "0123500005", "UkrName": "Вільшанка", "RusName": "Вільшанка", "EngName": "Vil'shanka", "EngName_Tr": "Vil'shanka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Полісський (відселений)", "DistrictR": "Полесский (отселенный)", "DistrictE": "Poliss'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.696960, 51.314930 ] } }
,
{ "type": "Feature", "properties": { "ID": "63", "SOATO_U": "0123500006", "UkrName": "Володимирівка", "RusName": "Владимировка", "EngName": "Volodymyrivka", "EngName_Tr": "Volodymyrivka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Полісський (відселений)", "DistrictR": "Полесский (отселенный)", "DistrictE": "Poliss'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.303700, 51.226650 ] } }
,
{ "type": "Feature", "properties": { "ID": "64", "SOATO_U": "0123500007", "UkrName": "Кливини", "RusName": "Кливины", "EngName": "Klyvyny", "EngName_Tr": "Klyvyny", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Полісський (відселений)", "DistrictR": "Полесский (отселенный)", "DistrictE": "Poliss'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.622130, 51.357660 ] } }
,
{ "type": "Feature", "properties": { "ID": "65", "SOATO_U": "0123500008", "UkrName": "Ковшилівка", "RusName": "Ковшилівка", "EngName": "Kovshylivka", "EngName_Tr": "Kovshylivka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Полісський (відселений)", "DistrictR": "Полесский (отселенный)", "DistrictE": "Poliss'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.514460, 51.270940 ] } }
,
{ "type": "Feature", "properties": { "ID": "66", "SOATO_U": "0123500009", "UkrName": "Лісництво Яковецьке", "RusName": "Лісництво Яковецьке", "EngName": "Lisnytstvo Yakovets'ke", "EngName_Tr": "Lisnytstvo Yakovets'ke", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Полісський (відселений)", "DistrictR": "Полесский (отселенный)", "DistrictE": "Poliss'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.613300, 51.396220 ] } }
,
{ "type": "Feature", "properties": { "ID": "67", "SOATO_U": "0123500010", "UkrName": "Луб'янка", "RusName": "Луб'янка", "EngName": "Lub'yanka", "EngName_Tr": "Lub'yanka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Полісський (відселений)", "DistrictR": "Полесский (отселенный)", "DistrictE": "Poliss'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.760300, 51.322270 ] } }
,
{ "type": "Feature", "properties": { "ID": "68", "SOATO_U": "0123500011", "UkrName": "Стара Рудня", "RusName": "Старая Рудня", "EngName": "Stara Rudnia", "EngName_Tr": "Stara Rudnia", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Полісський (відселений)", "DistrictR": "Полесский (отселенный)", "DistrictE": "Poliss'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.641750, 51.334100 ] } }
,
{ "type": "Feature", "properties": { "ID": "69", "SOATO_U": "0123700001", "UkrName": "Довгий Ліс", "RusName": "Долгий Лес", "EngName": "Dovhyi Lis", "EngName_Tr": "Dovhyi Lis", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Народицький (відселений)", "DistrictR": "Народичский (отселенный)", "DistrictE": "Narodyts'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.276550, 51.399400 ] } }
,
{ "type": "Feature", "properties": { "ID": "70", "SOATO_U": "0123700002", "UkrName": "Мотилі", "RusName": "Мотилі", "EngName": "Motyli", "EngName_Tr": "Motyli", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Народицький (відселений)", "DistrictR": "Народичский (отселенный)", "DistrictE": "Narodyts'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.273350, 51.436000 ] } }
,
{ "type": "Feature", "properties": { "ID": "71", "SOATO_U": "0123700003", "UkrName": "Нове Шарне", "RusName": "Нове Шарне", "EngName": "Nove Sharne", "EngName_Tr": "Nove Sharne", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Народицький (відселений)", "DistrictR": "Народичский (отселенный)", "DistrictE": "Narodyts'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.187470, 51.230470 ] } }
,
{ "type": "Feature", "properties": { "ID": "72", "SOATO_U": "0123700004", "UkrName": "Омельники", "RusName": "Омельники", "EngName": "Omel'nyky", "EngName_Tr": "Omel'nyky", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Народицький (відселений)", "DistrictR": "Народичский (отселенный)", "DistrictE": "Narodyts'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.243100, 51.387750 ] } }
,
{ "type": "Feature", "properties": { "ID": "73", "SOATO_U": "0124200001", "UkrName": "Деркачі", "RusName": "Деркачі", "EngName": "Derkachi", "EngName_Tr": "Derkachi", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Овруцький (відселений)", "DistrictR": "Овручский (отселенный)", "DistrictE": "Ovruts'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.038430, 51.408530 ] } }
,
{ "type": "Feature", "properties": { "ID": "74", "SOATO_U": "0124200002", "UkrName": "Журба", "RusName": "Журба", "EngName": "Zhurba", "EngName_Tr": "Zhurba", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Овруцький (відселений)", "DistrictR": "Овручский (отселенный)", "DistrictE": "Ovruts'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.118870, 51.402930 ] } }
,
{ "type": "Feature", "properties": { "ID": "75", "SOATO_U": "0124200003", "UkrName": "Липські Романи", "RusName": "Липські Романи", "EngName": "Lyps'ki Romany", "EngName_Tr": "Lyps'ki Romany", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Овруцький (відселений)", "DistrictR": "Овручский (отселенный)", "DistrictE": "Ovruts'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 29.048810, 51.416140 ] } }
,
{ "type": "Feature", "properties": { "ID": "516", "SOATO_U": "1822384201", "UkrName": "Обиходи", "RusName": "Обиходы", "EngName": "Obykhody", "EngName_Tr": "Obykhody", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Коростенський", "DistrictR": "Коростенский", "DistrictE": "Korostens'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 28.976930, 51.017960 ] } }
,
{ "type": "Feature", "properties": { "ID": "587", "SOATO_U": "1822881604", "UkrName": "Рудня-Жеревці", "RusName": "Рудня-Жеревцы", "EngName": "Rudnia-Zherevtsi", "EngName_Tr": "Rudnia-Zherevtsi", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Лугинський", "DistrictR": "Лугинский", "DistrictE": "Luhyns'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 28.170750, 51.159150 ] } }
,
{ "type": "Feature", "properties": { "ID": "597", "SOATO_U": "1822883202", "UkrName": "Малахівка", "RusName": "Малаховка", "EngName": "Malakhivka", "EngName_Tr": "Malakhivka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Лугинський", "DistrictR": "Лугинский", "DistrictE": "Luhyns'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 28.362960, 51.200310 ] } }
,
{ "type": "Feature", "properties": { "ID": "598", "SOATO_U": "1822883203", "UkrName": "Мощаниця", "RusName": "Мощаница", "EngName": "Moshchanytsia", "EngName_Tr": "Moshchanytsia", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Лугинський", "DistrictR": "Лугинский", "DistrictE": "Luhyns'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 28.488490, 51.215320 ] } }
,
{ "type": "Feature", "properties": { "ID": "604", "SOATO_U": "1822884403", "UkrName": "Рудня-Повчанська", "RusName": "Рудня-Повчанская", "EngName": "Rudnia-Povchans'ka", "EngName_Tr": "Rudnia-Povchans'ka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Лугинський", "DistrictR": "Лугинский", "DistrictE": "Luhyns'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 28.616430, 51.142480 ] } }
,
{ "type": "Feature", "properties": { "ID": "674", "SOATO_U": "1823484602", "UkrName": "Рудня-Калинівка", "RusName": "Рудня-Калиновка", "EngName": "Rudnia-Kalynivka", "EngName_Tr": "Rudnia-Kalynivka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Малинський", "DistrictR": "Малинский", "DistrictE": "Malyns'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.074610, 50.999580 ] } }
,
{ "type": "Feature", "properties": { "ID": "722", "SOATO_U": "1823755100", "UkrName": "Народичі", "RusName": "Народичи", "EngName": "Narodychi", "EngName_Tr": "Narodychi", "SettlType": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.086730, 51.210890 ] } }
,
{ "type": "Feature", "properties": { "ID": "723", "SOATO_U": "1823755101", "UkrName": "Старе Шарне", "RusName": "Старое Шарно", "EngName": "Stare Sharne", "EngName_Tr": "Stare Sharne", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.151570, 51.216170 ] } }
,
{ "type": "Feature", "properties": { "ID": "724", "SOATO_U": "1823780401", "UkrName": "Базар", "RusName": "Базар", "EngName": "Bazar", "EngName_Tr": "Bazar", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.294310, 51.045170 ] } }
,
{ "type": "Feature", "properties": { "ID": "725", "SOATO_U": "1823780403", "UkrName": "Великі Міньки", "RusName": "Великие Миньки", "EngName": "Velyki Min'ky", "EngName_Tr": "Velyki Min'ky", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.310120, 51.089530 ] } }
,
{ "type": "Feature", "properties": { "ID": "726", "SOATO_U": "1823780404", "UkrName": "Колосівка", "RusName": "Колосовка", "EngName": "Kolosivka", "EngName_Tr": "Kolosivka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.244610, 51.060380 ] } }
,
{ "type": "Feature", "properties": { "ID": "727", "SOATO_U": "1823780405", "UkrName": "Листвинівка", "RusName": "Листвиновка", "EngName": "Lystvynivka", "EngName_Tr": "Lystvynivka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.289520, 51.085030 ] } }
,
{ "type": "Feature", "properties": { "ID": "728", "SOATO_U": "1823780406", "UkrName": "Рудня-Базарська", "RusName": "Рудня-Базарская", "EngName": "Rudnia-Bazars'ka", "EngName_Tr": "Rudnia-Bazars'ka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.264540, 51.075620 ] } }
,
{ "type": "Feature", "properties": { "ID": "731", "SOATO_U": "1823781201", "UkrName": "Великі Кліщі", "RusName": "Великі Кліщі", "EngName": "Velyki Klishchi", "EngName_Tr": "Velyki Klishchi", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.176810, 51.065940 ] } }
,
{ "type": "Feature", "properties": { "ID": "732", "SOATO_U": "1823781202", "UkrName": "Поліське", "RusName": "Поліське", "EngName": "Polis'ke", "EngName_Tr": "Polis'ke", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.205160, 51.086060 ] } }
,
{ "type": "Feature", "properties": { "ID": "736", "SOATO_U": "1823782001", "UkrName": "Голубієвичі", "RusName": "Голубиевичи", "EngName": "Holubiievychi", "EngName_Tr": "Holubiievychi", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.404740, 51.090280 ] } }
,
{ "type": "Feature", "properties": { "ID": "738", "SOATO_U": "1823782003", "UkrName": "Васьківці", "RusName": "Васьковцы", "EngName": "Vas'kivtsi", "EngName_Tr": "Vas'kivtsi", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.384790, 51.112410 ] } }
,
{ "type": "Feature", "properties": { "ID": "740", "SOATO_U": "1823782005", "UkrName": "Заводне", "RusName": "Заводное", "EngName": "Zavodne", "EngName_Tr": "Zavodne", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.432060, 51.110910 ] } }
,
{ "type": "Feature", "properties": { "ID": "752", "SOATO_U": "1823784002", "UkrName": "Слобода", "RusName": "Слобода", "EngName": "Sloboda", "EngName_Tr": "Sloboda", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.158710, 51.021130 ] } }
,
{ "type": "Feature", "properties": { "ID": "753", "SOATO_U": "1823784003", "UkrName": "Малинка", "RusName": "Малинка", "EngName": "Malynka", "EngName_Tr": "Malynka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.179380, 51.005110 ] } }
,
{ "type": "Feature", "properties": { "ID": "755", "SOATO_U": "1823784801", "UkrName": "Любарка", "RusName": "Любарка", "EngName": "Liubarka", "EngName_Tr": "Liubarka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.064660, 51.077890 ] } }
,
{ "type": "Feature", "properties": { "ID": "756", "SOATO_U": "1823784802", "UkrName": "Журавлинка", "RusName": "Журавлинка", "EngName": "Zhuravlynka", "EngName_Tr": "Zhuravlynka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.014900, 51.057540 ] } }
,
{ "type": "Feature", "properties": { "ID": "757", "SOATO_U": "1823784803", "UkrName": "Калинівка", "RusName": "Калиновка", "EngName": "Kalynivka", "EngName_Tr": "Kalynivka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.089600, 51.022250 ] } }
,
{ "type": "Feature", "properties": { "ID": "758", "SOATO_U": "1823784804", "UkrName": "Роги", "RusName": "Роги", "EngName": "Rohy", "EngName_Tr": "Rohy", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.099480, 51.071420 ] } }
,
{ "type": "Feature", "properties": { "ID": "759", "SOATO_U": "1823784805", "UkrName": "Северівка", "RusName": "Северовка", "EngName": "Severivka", "EngName_Tr": "Severivka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.073460, 51.104110 ] } }
,
{ "type": "Feature", "properties": { "ID": "760", "SOATO_U": "1823785301", "UkrName": "Малі Кліщі", "RusName": "Малі Кліщі", "EngName": "Mali Klishchi", "EngName_Tr": "Mali Klishchi", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.162340, 51.123520 ] } }
,
{ "type": "Feature", "properties": { "ID": "761", "SOATO_U": "1823785302", "UkrName": "Перемога", "RusName": "Перемога", "EngName": "Peremoha", "EngName_Tr": "Peremoha", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.196150, 51.126310 ] } }
,
{ "type": "Feature", "properties": { "ID": "762", "SOATO_U": "1823785303", "UkrName": "Хрипля", "RusName": "Хрипля", "EngName": "Khryplia", "EngName_Tr": "Khryplia", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.244410, 51.106080 ] } }
,
{ "type": "Feature", "properties": { "ID": "763", "SOATO_U": "1823785701", "UkrName": "Звіздаль", "RusName": "Звіздаль", "EngName": "Zvizdal'", "EngName_Tr": "Zvizdal'", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.244360, 51.173240 ] } }
,
{ "type": "Feature", "properties": { "ID": "764", "SOATO_U": "1823785702", "UkrName": "Малі Міньки", "RusName": "Малі Міньки", "EngName": "Mali Min'ky", "EngName_Tr": "Mali Min'ky", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.271750, 51.139440 ] } }
,
{ "type": "Feature", "properties": { "ID": "765", "SOATO_U": "1823785703", "UkrName": "Шишелівка", "RusName": "Шишелівка", "EngName": "Shyshelivka", "EngName_Tr": "Shyshelivka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.243500, 51.141780 ] } }
,
{ "type": "Feature", "properties": { "ID": "766", "SOATO_U": "1823785704", "UkrName": "Рудня-Осошня", "RusName": "Рудня-Осошня", "EngName": "Rudnia-Ososhnia", "EngName_Tr": "Rudnia-Ososhnia", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.351670, 51.150020 ] } }
,
{ "type": "Feature", "properties": { "ID": "767", "SOATO_U": "1823786001", "UkrName": "Межиліска", "RusName": "Межилеска", "EngName": "Mezhyliska", "EngName_Tr": "Mezhyliska", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.365030, 51.053560 ] } }
,
{ "type": "Feature", "properties": { "ID": "768", "SOATO_U": "1823786002", "UkrName": "Карпилівка", "RusName": "Карпиловка", "EngName": "Karpylivka", "EngName_Tr": "Karpylivka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.367150, 51.047620 ] } }
,
{ "type": "Feature", "properties": { "ID": "769", "SOATO_U": "1823786003", "UkrName": "Осика", "RusName": "Осыка", "EngName": "Osyka", "EngName_Tr": "Osyka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.369600, 51.083090 ] } }
,
{ "type": "Feature", "properties": { "ID": "786", "SOATO_U": "1823787301", "UkrName": "Розсохівське", "RusName": "Рассоховское", "EngName": "Rozsokhivs'ke", "EngName_Tr": "Rozsokhivs'ke", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.011780, 51.129020 ] } }
,
{ "type": "Feature", "properties": { "ID": "788", "SOATO_U": "1823787303", "UkrName": "Ганнівка", "RusName": "Анновка", "EngName": "Hannivka", "EngName_Tr": "Hannivka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.045830, 51.148830 ] } }
,
{ "type": "Feature", "properties": { "ID": "791", "SOATO_U": "1823787309", "UkrName": "Лозниця", "RusName": "Лозница", "EngName": "Loznytsia", "EngName_Tr": "Loznytsia", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.087950, 51.124160 ] } }
,
{ "type": "Feature", "properties": { "ID": "792", "SOATO_U": "1823787401", "UkrName": "Селець", "RusName": "Селец", "EngName": "Selets'", "EngName_Tr": "Selets'", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.031280, 51.187410 ] } }
,
{ "type": "Feature", "properties": { "ID": "793", "SOATO_U": "1823787402", "UkrName": "Булів", "RusName": "Булев", "EngName": "Buliv", "EngName_Tr": "Buliv", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.043890, 51.170220 ] } }
,
{ "type": "Feature", "properties": { "ID": "800", "SOATO_U": "1823788207", "UkrName": "Христинівка", "RusName": "Христиновка", "EngName": "Khrystynivka", "EngName_Tr": "Khrystynivka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.208440, 51.241420 ] } }
,
{ "type": "Feature", "properties": { "ID": "801", "SOATO_U": "1823788209", "UkrName": "Ноздрище", "RusName": "Ноздрище", "EngName": "Nozdryshche", "EngName_Tr": "Nozdryshche", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Народицький", "DistrictR": "Народичский", "DistrictE": "Narodyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.176280, 51.244100 ] } }
,
{ "type": "Feature", "properties": { "ID": "842", "SOATO_U": "1824280302", "UkrName": "Делета", "RusName": "Делета", "EngName": "Deleta", "EngName_Tr": "Deleta", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Овруцький", "DistrictR": "Овручский", "DistrictE": "Ovruts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 28.240750, 51.630460 ] } }
,
{ "type": "Feature", "properties": { "ID": "861", "SOATO_U": "1824281601", "UkrName": "Виступовичі", "RusName": "Выступовичи", "EngName": "Vystupovychi", "EngName_Tr": "Vystupovychi", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Овруцький", "DistrictR": "Овручский", "DistrictE": "Ovruts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.075910, 51.564070 ] } }
,
{ "type": "Feature", "properties": { "ID": "862", "SOATO_U": "1824281602", "UkrName": "Борутине", "RusName": "Борутино", "EngName": "Borutyne", "EngName_Tr": "Borutyne", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Овруцький", "DistrictR": "Овручский", "DistrictE": "Ovruts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.136220, 51.615710 ] } }
,
{ "type": "Feature", "properties": { "ID": "863", "SOATO_U": "1824281603", "UkrName": "Солотине", "RusName": "Солотино", "EngName": "Solotyne", "EngName_Tr": "Solotyne", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Овруцький", "DistrictR": "Овручский", "DistrictE": "Ovruts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.157930, 51.565150 ] } }
,
{ "type": "Feature", "properties": { "ID": "867", "SOATO_U": "1824281904", "UkrName": "Олександри", "RusName": "Александры", "EngName": "Oleksandry", "EngName_Tr": "Oleksandry", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Овруцький", "DistrictR": "Овручский", "DistrictE": "Ovruts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 28.957420, 51.410250 ] } }
,
{ "type": "Feature", "properties": { "ID": "878", "SOATO_U": "1824282401", "UkrName": "Переїзд", "RusName": "Переезд", "EngName": "Pereizd", "EngName_Tr": "Pereizd", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Овруцький", "DistrictR": "Овручский", "DistrictE": "Ovruts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.145750, 51.377560 ] } }
,
{ "type": "Feature", "properties": { "ID": "883", "SOATO_U": "1824282411", "UkrName": "Маленівка", "RusName": "Маленовка", "EngName": "Malenivka", "EngName_Tr": "Malenivka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Овруцький", "DistrictR": "Овручский", "DistrictE": "Ovruts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.112620, 51.412150 ] } }
,
{ "type": "Feature", "properties": { "ID": "885", "SOATO_U": "1824282419", "UkrName": "Соснівка", "RusName": "Сосновка", "EngName": "Sosnivka", "EngName_Tr": "Sosnivka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Овруцький", "DistrictR": "Овручский", "DistrictE": "Ovruts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.099700, 51.385550 ] } }
,
{ "type": "Feature", "properties": { "ID": "886", "SOATO_U": "1824282421", "UkrName": "Степки", "RusName": "Степки", "EngName": "Stepky", "EngName_Tr": "Stepky", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Овруцький", "DistrictR": "Овручский", "DistrictE": "Ovruts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.153640, 51.419650 ] } }
,
{ "type": "Feature", "properties": { "ID": "892", "SOATO_U": "1824282705", "UkrName": "Млини", "RusName": "Млыны", "EngName": "Mlyny", "EngName_Tr": "Mlyny", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Овруцький", "DistrictR": "Овручский", "DistrictE": "Ovruts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 28.661440, 51.138960 ] } }
,
{ "type": "Feature", "properties": { "ID": "902", "SOATO_U": "1824283701", "UkrName": "Колесники", "RusName": "Колесники", "EngName": "Kolesnyky", "EngName_Tr": "Kolesnyky", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Овруцький", "DistrictR": "Овручский", "DistrictE": "Ovruts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.008640, 51.400710 ] } }
,
{ "type": "Feature", "properties": { "ID": "906", "SOATO_U": "1824283709", "UkrName": "Сидори", "RusName": "Сидоры", "EngName": "Sydory", "EngName_Tr": "Sydory", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Овруцький", "DistrictR": "Овручский", "DistrictE": "Ovruts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.043400, 51.387150 ] } }
,
{ "type": "Feature", "properties": { "ID": "907", "SOATO_U": "1824283711", "UkrName": "Стовпичне", "RusName": "Столпичное", "EngName": "Stovpychne", "EngName_Tr": "Stovpychne", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Овруцький", "DistrictR": "Овручский", "DistrictE": "Ovruts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.011460, 51.380810 ] } }
,
{ "type": "Feature", "properties": { "ID": "917", "SOATO_U": "1824284703", "UkrName": "Червоносілка", "RusName": "Червоноселка", "EngName": "Chervonosilka", "EngName_Tr": "Chervonosilka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Овруцький", "DistrictR": "Овручский", "DistrictE": "Ovruts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 28.294180, 51.582500 ] } }
,
{ "type": "Feature", "properties": { "ID": "952", "SOATO_U": "1824286701", "UkrName": "Рудня", "RusName": "Рудня", "EngName": "Rudnia", "EngName_Tr": "Rudnia", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Овруцький", "DistrictR": "Овручский", "DistrictE": "Ovruts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 28.966700, 51.506840 ] } }
,
{ "type": "Feature", "properties": { "ID": "955", "SOATO_U": "1824286704", "UkrName": "Думинське", "RusName": "Думинское", "EngName": "Dumyns'ke", "EngName_Tr": "Dumyns'ke", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Овруцький", "DistrictR": "Овручский", "DistrictE": "Ovruts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 28.905390, 51.529420 ] } }
,
{ "type": "Feature", "properties": { "ID": "956", "SOATO_U": "1824286705", "UkrName": "Людвинівка", "RusName": "Людвиновка", "EngName": "Liudvynivka", "EngName_Tr": "Liudvynivka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Овруцький", "DistrictR": "Овручский", "DistrictE": "Ovruts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.053970, 51.509530 ] } }
,
{ "type": "Feature", "properties": { "ID": "957", "SOATO_U": "1824286706", "UkrName": "Піхоцьке", "RusName": "Пехотское", "EngName": "Pikhots'ke", "EngName_Tr": "Pikhots'ke", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Овруцький", "DistrictR": "Овручский", "DistrictE": "Ovruts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 28.943880, 51.532390 ] } }
,
{ "type": "Feature", "properties": { "ID": "984", "SOATO_U": "1824288203", "UkrName": "Возлякове", "RusName": "Возляково", "EngName": "Vozliakove", "EngName_Tr": "Vozliakove", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Овруцький", "DistrictR": "Овручский", "DistrictE": "Ovruts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 28.304770, 51.211730 ] } }
,
{ "type": "Feature", "properties": { "ID": "996", "SOATO_U": "1824455300", "UkrName": "Діброва", "RusName": "Диброва", "EngName": "Dibrova", "EngName_Tr": "Dibrova", "SettlType": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Олевський", "DistrictR": "Олевский", "DistrictE": "Olevs'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 27.988720, 51.152290 ] } }
,
{ "type": "Feature", "properties": { "ID": "1035", "SOATO_U": "1824486004", "UkrName": "Рудня-Радовельська", "RusName": "Рудня-Радовельская", "EngName": "Rudnia-Radovel's'ka", "EngName_Tr": "Rudnia-Radovel's'ka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Житомирська", "OblastR": "Житомирская", "OblastE": "Zhytomyrs'ka", "OblastE_Tr": "Zhytomyr", "District": "Олевський", "DistrictR": "Олевский", "DistrictE": "Olevs'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 27.895410, 51.173400 ] } }
,
{ "type": "Feature", "properties": { "ID": "1437", "SOATO_U": "3223555100", "UkrName": "Поліське", "RusName": "Полесское", "EngName": "Poliss'ke", "EngName_Tr": "Poliss'ke", "SettlType": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "Oblast": "Київська", "OblastR": "Киевская", "OblastE": "Kyivs'ka", "OblastE_Tr": "Kyiv", "District": "Полісський", "DistrictR": "Полесский", "DistrictE": "Poliss'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.412000, 51.236800 ] } }
,
{ "type": "Feature", "properties": { "ID": "1438", "SOATO_U": "3223555102", "UkrName": "Діброва", "RusName": "Диброва", "EngName": "Dibrova", "EngName_Tr": "Dibrova", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Київська", "OblastR": "Киевская", "OblastE": "Kyivs'ka", "OblastE_Tr": "Kyiv", "District": "Полісський", "DistrictR": "Полесский", "DistrictE": "Poliss'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.687690, 51.282020 ] } }
,
{ "type": "Feature", "properties": { "ID": "1439", "SOATO_U": "3223555103", "UkrName": "Грезля", "RusName": "Грезля", "EngName": "Hrezlia", "EngName_Tr": "Hrezlia", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Київська", "OblastR": "Киевская", "OblastE": "Kyivs'ka", "OblastE_Tr": "Kyiv", "District": "Полісський", "DistrictR": "Полесский", "DistrictE": "Poliss'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.447860, 51.257840 ] } }
,
{ "type": "Feature", "properties": { "ID": "1440", "SOATO_U": "3223555107", "UkrName": "Жовтневе", "RusName": "Жовтневое", "EngName": "Zhovtneve", "EngName_Tr": "Zhovtneve", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Київська", "OblastR": "Киевская", "OblastE": "Kyivs'ka", "OblastE_Tr": "Kyiv", "District": "Полісський", "DistrictR": "Полесский", "DistrictE": "Poliss'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.330540, 51.203930 ] } }
,
{ "type": "Feature", "properties": { "ID": "1441", "SOATO_U": "3223555108", "UkrName": "Мартиновичі", "RusName": "Мартыновичи", "EngName": "Martynovychi", "EngName_Tr": "Martynovychi", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Київська", "OblastR": "Киевская", "OblastE": "Kyivs'ka", "OblastE_Tr": "Kyiv", "District": "Полісський", "DistrictR": "Полесский", "DistrictE": "Poliss'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.645720, 51.264300 ] } }
,
{ "type": "Feature", "properties": { "ID": "1442", "SOATO_U": "3223555109", "UkrName": "Рудня Грезлянська", "RusName": "Рудня Грезлянская", "EngName": "Rudnia Hrezlians'ka", "EngName_Tr": "Rudnia Hrezlians'ka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Київська", "OblastR": "Киевская", "OblastE": "Kyivs'ka", "OblastE_Tr": "Kyiv", "District": "Полісський", "DistrictR": "Полесский", "DistrictE": "Poliss'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.454180, 51.256650 ] } }
,
{ "type": "Feature", "properties": { "ID": "1443", "SOATO_U": "3223555111", "UkrName": "Тараси", "RusName": "Тарасы", "EngName": "Tarasy", "EngName_Tr": "Tarasy", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Київська", "OblastR": "Киевская", "OblastE": "Kyivs'ka", "OblastE_Tr": "Kyiv", "District": "Полісський", "DistrictR": "Полесский", "DistrictE": "Poliss'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.308410, 51.258630 ] } }
,
{ "type": "Feature", "properties": { "ID": "1444", "SOATO_U": "3223555200", "UkrName": "Вільча", "RusName": "Вильча", "EngName": "Vil'cha", "EngName_Tr": "Vil'cha", "SettlType": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "Oblast": "Київська", "OblastR": "Киевская", "OblastE": "Kyivs'ka", "OblastE_Tr": "Kyiv", "District": "Полісський", "DistrictR": "Полесский", "DistrictE": "Poliss'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.447800, 51.357870 ] } }
,
{ "type": "Feature", "properties": { "ID": "1445", "SOATO_U": "3223556011", "UkrName": "Буда Варовичі", "RusName": "Буда Варовичи", "EngName": "Buda Varovychi", "EngName_Tr": "Buda Varovychi", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Київська", "OblastR": "Киевская", "OblastE": "Kyivs'ka", "OblastE_Tr": "Kyiv", "District": "Полісський", "DistrictR": "Полесский", "DistrictE": "Poliss'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.483450, 51.323290 ] } }
,
{ "type": "Feature", "properties": { "ID": "1446", "SOATO_U": "3223556012", "UkrName": "Денисовичі", "RusName": "Денисовичи", "EngName": "Denysovychi", "EngName_Tr": "Denysovychi", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Київська", "OblastR": "Киевская", "OblastE": "Kyivs'ka", "OblastE_Tr": "Kyiv", "District": "Полісський", "DistrictR": "Полесский", "DistrictE": "Poliss'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.707010, 51.483420 ] } }
,
{ "type": "Feature", "properties": { "ID": "1447", "SOATO_U": "3223556013", "UkrName": "Новий Мир", "RusName": "Новий Мир", "EngName": "Novyi Myr", "EngName_Tr": "Novyi Myr", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Київська", "OblastR": "Киевская", "OblastE": "Kyivs'ka", "OblastE_Tr": "Kyiv", "District": "Полісський", "DistrictR": "Полесский", "DistrictE": "Poliss'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.583360, 51.332490 ] } }
,
{ "type": "Feature", "properties": { "ID": "1448", "SOATO_U": "3223556014", "UkrName": "Становище", "RusName": "Становище", "EngName": "Stanovyshche", "EngName_Tr": "Stanovyshche", "SettlType": "селище", "SettlTypeR": "поселок", "SettlTypeE": "s. village", "Oblast": "Київська", "OblastR": "Киевская", "OblastE": "Kyivs'ka", "OblastE_Tr": "Kyiv", "District": "Полісський", "DistrictR": "Полесский", "DistrictE": "Poliss'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.385330, 51.386590 ] } }
,
{ "type": "Feature", "properties": { "ID": "1454", "SOATO_U": "3223581603", "UkrName": "Пухове", "RusName": "Пуховое", "EngName": "Pukhove", "EngName_Tr": "Pukhove", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Київська", "OblastR": "Киевская", "OblastE": "Kyivs'ka", "OblastE_Tr": "Kyiv", "District": "Полісський", "DistrictR": "Полесский", "DistrictE": "Poliss'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.536570, 51.131680 ] } }
,
{ "type": "Feature", "properties": { "ID": "1462", "SOATO_U": "3223585202", "UkrName": "Стеблі", "RusName": "Стебли", "EngName": "Stebli", "EngName_Tr": "Stebli", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Київська", "OblastR": "Киевская", "OblastE": "Kyivs'ka", "OblastE_Tr": "Kyiv", "District": "Полісський", "DistrictR": "Полесский", "DistrictE": "Poliss'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.446030, 51.230840 ] } }
,
{ "type": "Feature", "properties": { "ID": "1463", "SOATO_U": "3223585203", "UkrName": "Фабриківка", "RusName": "Фабриковка", "EngName": "Fabrykivka", "EngName_Tr": "Fabrykivka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Київська", "OblastR": "Киевская", "OblastE": "Kyivs'ka", "OblastE_Tr": "Kyiv", "District": "Полісський", "DistrictR": "Полесский", "DistrictE": "Poliss'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.461800, 51.231960 ] } }
,
{ "type": "Feature", "properties": { "ID": "1466", "SOATO_U": "3223585602", "UkrName": "Королівка", "RusName": "Королевка", "EngName": "Korolivka", "EngName_Tr": "Korolivka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Київська", "OblastR": "Киевская", "OblastE": "Kyivs'ka", "OblastE_Tr": "Kyiv", "District": "Полісський", "DistrictR": "Полесский", "DistrictE": "Poliss'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.615200, 51.163180 ] } }
,
{ "type": "Feature", "properties": { "ID": "1474", "SOATO_U": "3223587602", "UkrName": "Котовське", "RusName": "Котовское", "EngName": "Kotovs'ke", "EngName_Tr": "Kotovs'ke", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Київська", "OblastR": "Киевская", "OblastE": "Kyivs'ka", "OblastE_Tr": "Kyiv", "District": "Полісський", "DistrictR": "Полесский", "DistrictE": "Poliss'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.369090, 51.194650 ] } }
,
{ "type": "Feature", "properties": { "ID": "1475", "SOATO_U": "3223587603", "UkrName": "Шевченкове", "RusName": "Шевченково", "EngName": "Shevchenkove", "EngName_Tr": "Shevchenkove", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Київська", "OblastR": "Киевская", "OblastE": "Kyivs'ka", "OblastE_Tr": "Kyiv", "District": "Полісський", "DistrictR": "Полесский", "DistrictE": "Poliss'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.396820, 51.175000 ] } }
,
{ "type": "Feature", "properties": { "ID": "1476", "SOATO_U": "3223587604", "UkrName": "Ясен", "RusName": "Ясен", "EngName": "Yasen", "EngName_Tr": "Yasen", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Київська", "OblastR": "Киевская", "OblastE": "Kyivs'ka", "OblastE_Tr": "Kyiv", "District": "Полісський", "DistrictR": "Полесский", "DistrictE": "Poliss'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.438120, 51.167360 ] } }
,
{ "type": "Feature", "properties": { "ID": "1485", "SOATO_U": "3223589203", "UkrName": "Нова Марківка", "RusName": "Новая Марковка", "EngName": "Nova Markivka", "EngName_Tr": "Nova Markivka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Київська", "OblastR": "Киевская", "OblastE": "Kyivs'ka", "OblastE_Tr": "Kyiv", "District": "Полісський", "DistrictR": "Полесский", "DistrictE": "Poliss'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 29.494150, 51.136850 ] } }
,
{ "type": "Feature", "properties": { "ID": "1708", "SOATO_U": "5621886402", "UkrName": "Будимля", "RusName": "Будымля", "EngName": "Budymlia", "EngName_Tr": "Budymlia", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Рівненська", "OblastR": "Ровенская", "OblastE": "Rivnens'ka", "OblastE_Tr": "Rivne", "District": "Дубровицький", "DistrictR": "Дубровицкий", "DistrictE": "Dubrovyts'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 26.976450, 51.668940 ] } }
,
{ "type": "Feature", "properties": { "ID": "2108", "SOATO_U": "7424482509", "UkrName": "Редьківка", "RusName": "Редьковка", "EngName": "Red'kivka", "EngName_Tr": "Red'kivka", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Чернігівська", "OblastR": "Черниговская", "OblastE": "Chernihivs'ka", "OblastE_Tr": "Chernihiv", "District": "Ріпкинський", "DistrictR": "Репкинский", "DistrictE": "Ripkyns'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 30.598540, 51.614520 ] } }
,
{ "type": "Feature", "properties": { "ID": "2253", "SOATO_U": "7425586305", "UkrName": "Локотьків", "RusName": "Локотьков", "EngName": "Lokot'kiv", "EngName_Tr": "Lokot'kiv", "SettlType": "село", "SettlTypeR": "село", "SettlTypeE": "village", "Oblast": "Чернігівська", "OblastR": "Черниговская", "OblastE": "Chernihivs'ka", "OblastE_Tr": "Chernihiv", "District": "Чернігівський", "DistrictR": "Черниговский", "DistrictE": "Chernihivs'kyi", "Zone": "2" }, "geometry": { "type": "Point", "coordinates": [ 30.836870, 51.426090 ] } }
,
{ "type": "Feature", "properties": { "ID": "2291", "SOATO_U": "0120100056", "UkrName": "Чорнобиль-2", "RusName": "Чернобыль-2", "EngName": "Chornobyl'-2", "EngName_Tr": "Chornobyl'-2", "SettlType": "селище", "SettlTypeR": "поселок", "SettlTypeE": "s. village", "Oblast": "Зона Відчуження", "OblastR": "Зона отчуждения", "OblastE": "Exclusion Zone", "OblastE_Tr": "Exclusion Zone", "District": "Чорнобильський (відселений)", "DistrictR": "Чернобыльский (отселенный)", "DistrictE": "Chornobyl's'kyi (resettled)", "Zone": "1" }, "geometry": { "type": "Point", "coordinates": [ 30.181275, 51.279398 ] } }

]
}
