var Layer_24088287_091098_75_01 = {
"type": "FeatureCollection",
"features": [
{ "type": "Feature", "properties": { "ID": "1", "SOATO_U": "", "UkrName": "Тетерів", "RusName": "Тетерев", "EngName": "Teteriv", "EngName_Tr": "Teteriv", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 29.598240, 50.699190 ] } }
,
{ "type": "Feature", "properties": { "ID": "2", "SOATO_U": "0120100055", "UkrName": "Чорнобиль", "RusName": "Чернобыль", "EngName": "Chornobyl'", "EngName_Tr": "Chornobyl'", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,2,3,", "Observ": "атмосферні випадання, повітряні аерозолі, потужність експозиційної дози гамма-випромінювання", "ObservR": "", "ObservE": "" }, "geometry": { "type": "Point", "coordinates": [ 30.225790, 51.267240 ] } }
,
{ "type": "Feature", "properties": { "ID": "3", "SOATO_U": "0520850100", "UkrName": "Гайсин", "RusName": "Гайсин", "EngName": "Haisyn", "EngName_Tr": "Haisyn", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 29.407610, 48.797160 ] } }
,
{ "type": "Feature", "properties": { "ID": "4", "SOATO_U": "0521480403", "UkrName": "Бiлопiлля", "RusName": "Белополье", "EngName": "Bilopillia", "EngName_Tr": "Bilopillia", "Settltype": "село", "SettlTypeR": "село", "SettlTypeE": "village", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 28.867850, 49.843360 ] } }
,
{ "type": "Feature", "properties": { "ID": "5", "SOATO_U": "0540100000", "UkrName": "Вiнниця", "RusName": "Винница", "EngName": "Vinnytsia", "EngName_Tr": "Vinnytsia", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 28.479960, 49.224120 ] } }
,
{ "type": "Feature", "properties": { "ID": "6", "SOATO_U": "0540300000", "UkrName": "Жмеринка", "RusName": "Жмеринка", "EngName": "Zhmerynka", "EngName_Tr": "Zhmerynka", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 28.123420, 49.041840 ] } }
,
{ "type": "Feature", "properties": { "ID": "7", "SOATO_U": "0540400000", "UkrName": "Могилiв-Подiльський", "RusName": "Могилев-Подольский", "EngName": "Mohyliv-Podil's'kyi", "EngName_Tr": "Mohyliv-Podil's'kyi", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 27.820860, 48.446910 ] } }
,
{ "type": "Feature", "properties": { "ID": "8", "SOATO_U": "0540900000", "UkrName": "Хмiльник", "RusName": "Хмельник", "EngName": "Khmil'nyk", "EngName_Tr": "Khmil'nyk", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 27.957220, 49.555950 ] } }
,
{ "type": "Feature", "properties": { "ID": "9", "SOATO_U": "0723155100", "UkrName": "Любешiв", "RusName": "Любешов", "EngName": "Liubeshiv", "EngName_Tr": "Liubeshiv", "Settltype": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 25.520670, 51.764500 ] } }
,
{ "type": "Feature", "properties": { "ID": "10", "SOATO_U": "0723655100", "UkrName": "Маневичi", "RusName": "Маневичи", "EngName": "Manevychi", "EngName_Tr": "Manevychi", "Settltype": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 25.521100, 51.301300 ] } }
,
{ "type": "Feature", "properties": { "ID": "11", "SOATO_U": "0725785601", "UkrName": "Свiтязь", "RusName": "Свитязь", "EngName": "Svitiaz'", "EngName_Tr": "Svitiaz'", "Settltype": "село", "SettlTypeR": "село", "SettlTypeE": "village", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 23.859350, 51.480610 ] } }
,
{ "type": "Feature", "properties": { "ID": "12", "SOATO_U": "0740100000", "UkrName": "Луцьк", "RusName": "Луцк", "EngName": "Luts'k", "EngName_Tr": "Lutsk", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 25.344830, 50.765460 ] } }
,
{ "type": "Feature", "properties": { "ID": "13", "SOATO_U": "0740200000", "UkrName": "Володимир-Волинський", "RusName": "Владимир-Волынский", "EngName": "Volodymyr-Volyns'kyi", "EngName_Tr": "Volodymyr-Volyns'kyi", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 24.319160, 50.856820 ] } }
,
{ "type": "Feature", "properties": { "ID": "14", "SOATO_U": "0740400000", "UkrName": "Ковель", "RusName": "Ковель", "EngName": "Kovel'", "EngName_Tr": "Kovel'", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 24.713370, 51.218060 ] } }
,
{ "type": "Feature", "properties": { "ID": "15", "SOATO_U": "0920655100", "UkrName": "Бiловодськ", "RusName": "Беловодск", "EngName": "Bilovods'k", "EngName_Tr": "Bilovods'k", "Settltype": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 39.580720, 49.228330 ] } }
,
{ "type": "Feature", "properties": { "ID": "16", "SOATO_U": "0923885201", "UkrName": "Троїцьке", "RusName": "Троицкое", "EngName": "Troits'ke", "EngName_Tr": "Troits'ke", "Settltype": "село", "SettlTypeR": "село", "SettlTypeE": "village", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 38.371940, 48.525540 ] } }
,
{ "type": "Feature", "properties": { "ID": "17", "SOATO_U": "0924050100", "UkrName": "Сватове", "RusName": "Сватово", "EngName": "Svatove", "EngName_Tr": "Svatove", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 38.162540, 49.418580 ] } }
,
{ "type": "Feature", "properties": { "ID": "18", "SOATO_U": "0924286603", "UkrName": "Дар'ївка", "RusName": "Дарьевка", "EngName": "Dar'ivka", "EngName_Tr": "Dar'ivka", "Settltype": "село", "SettlTypeR": "село", "SettlTypeE": "village", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 39.434510, 47.984790 ] } }
,
{ "type": "Feature", "properties": { "ID": "19", "SOATO_U": "0940100000", "UkrName": "Луганськ", "RusName": "Луганск", "EngName": "Luhans'k", "EngName_Tr": "Luhansk", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 39.321550, 48.536390 ] } }
,
{ "type": "Feature", "properties": { "ID": "20", "SOATO_U": "0942900000", "UkrName": "Сєверодонецьк", "RusName": "Северодонецк", "EngName": "Sieverodonets'k", "EngName_Tr": "Sievierodonets'k", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 38.481430, 48.954840 ] } }
,
{ "type": "Feature", "properties": { "ID": "21", "SOATO_U": "1220755700", "UkrName": "Чаплине", "RusName": "Чаплино", "EngName": "Chaplyne", "EngName_Tr": "Chaplyne", "Settltype": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 36.232870, 48.116860 ] } }
,
{ "type": "Feature", "properties": { "ID": "22", "SOATO_U": "1223255600", "UkrName": "Губиниха", "RusName": "Губиниха", "EngName": "Hubynykha", "EngName_Tr": "Hubynykha", "Settltype": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 35.267900, 48.811960 ] } }
,
{ "type": "Feature", "properties": { "ID": "23", "SOATO_U": "1224582001", "UkrName": "Комiсарiвка", "RusName": "Комиссаровка", "EngName": "Komisarivka", "EngName_Tr": "Komisarivka", "Settltype": "село", "SettlTypeR": "село", "SettlTypeE": "village", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 33.802230, 48.466110 ] } }
,
{ "type": "Feature", "properties": { "ID": "24", "SOATO_U": "1225284407", "UkrName": "Лошкарiвка", "RusName": "Лошкаревка", "EngName": "Loshkarivka", "EngName_Tr": "Loshkarivka", "Settltype": "селище", "SettlTypeR": "поселок", "SettlTypeE": "s. village", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 34.173240, 47.974480 ] } }
,
{ "type": "Feature", "properties": { "ID": "25", "SOATO_U": "1240100000", "UkrName": "Днiпропетровськ", "RusName": "Днепропетровск", "EngName": "Dnipropetrovs'k", "EngName_Tr": "Dnipropetrovsk", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 34.974840, 48.433860 ] } }
,
{ "type": "Feature", "properties": { "ID": "26", "SOATO_U": "1240400000", "UkrName": "Днiпродзержинськ", "RusName": "Днепродзержинск", "EngName": "Dniprodzerzhyns'k", "EngName_Tr": "Dniprodzerzhyns'k", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 34.616630, 48.496840 ] } }
,
{ "type": "Feature", "properties": { "ID": "27", "SOATO_U": "1241000000", "UkrName": "Кривий Рiг", "RusName": "Кривой Рог", "EngName": "Kryvyi Rih", "EngName_Tr": "Kryvyi Rih", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 33.457670, 48.024390 ] } }
,
{ "type": "Feature", "properties": { "ID": "28", "SOATO_U": "1241600000", "UkrName": "Нiкополь", "RusName": "Никополь", "EngName": "Nikopol'", "EngName_Tr": "Nikopol'", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 34.417480, 47.578300 ] } }
,
{ "type": "Feature", "properties": { "ID": "29", "SOATO_U": "1242400000", "UkrName": "Павлоград", "RusName": "Павлоград", "EngName": "Pavlohrad", "EngName_Tr": "Pavlohrad", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 35.916060, 48.524610 ] } }
,
{ "type": "Feature", "properties": { "ID": "30", "SOATO_U": "1243000000", "UkrName": "Синельникове", "RusName": "Синельниково", "EngName": "Synel'nykove", "EngName_Tr": "Synel'nykove", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 35.522480, 48.322540 ] } }
,
{ "type": "Feature", "properties": { "ID": "31", "SOATO_U": "1420650100", "UkrName": "Амвросiївка", "RusName": "Амвросиевка", "EngName": "Amvrosiivka", "EngName_Tr": "Amvrosiivka", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 38.500100, 47.804010 ] } }
,
{ "type": "Feature", "properties": { "ID": "32", "SOATO_U": "1421550100", "UkrName": "Волноваха", "RusName": "Волноваха", "EngName": "Volnovakha", "EngName_Tr": "Volnovakha", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 37.501230, 47.600160 ] } }
,
{ "type": "Feature", "properties": { "ID": "33", "SOATO_U": "1424280307", "UkrName": "Красноармiйське", "RusName": "Красноармейское", "EngName": "Krasnoarmiis'ke", "EngName_Tr": "Krasnoarmiis'ke", "Settltype": "село", "SettlTypeR": "село", "SettlTypeE": "village", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 37.478730, 48.818030 ] } }
,
{ "type": "Feature", "properties": { "ID": "34", "SOATO_U": "1440100000", "UkrName": "Донецьк", "RusName": "Донецк", "EngName": "Donets'k", "EngName_Tr": "Donetsk", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 37.707430, 48.004360 ] } }
,
{ "type": "Feature", "properties": { "ID": "35", "SOATO_U": "1440300000", "UkrName": "Артемiвськ", "RusName": "Артемовск", "EngName": "Artemivs'k", "EngName_Tr": "Artemivs'k", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 38.006150, 48.605290 ] } }
,
{ "type": "Feature", "properties": { "ID": "36", "SOATO_U": "1440900000", "UkrName": "Дебальцеве", "RusName": "Дебальцево", "EngName": "Debal'tseve", "EngName_Tr": "Debal'tseve", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 38.451620, 48.371860 ] } }
,
{ "type": "Feature", "properties": { "ID": "37", "SOATO_U": "1442300000", "UkrName": "Марiуполь", "RusName": "Мариуполь", "EngName": "Mariupol'", "EngName_Tr": "Mariupol'", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 37.597670, 47.137420 ] } }
,
{ "type": "Feature", "properties": { "ID": "38", "SOATO_U": "1824250100", "UkrName": "Овруч", "RusName": "Овруч", "EngName": "Ovruch", "EngName_Tr": "Ovruch", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 28.824430, 51.319450 ] } }
,
{ "type": "Feature", "properties": { "ID": "39", "SOATO_U": "1824455100", "UkrName": "Олевськ", "RusName": "Олевск", "EngName": "Olevs'k", "EngName_Tr": "Olevs'k", "Settltype": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 27.644710, 51.232030 ] } }
,
{ "type": "Feature", "properties": { "ID": "40", "SOATO_U": "1840100000", "UkrName": "Житомир", "RusName": "Житомир", "EngName": "Zhytomyr", "EngName_Tr": "Zhytomyr", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 28.694220, 50.252750 ] } }
,
{ "type": "Feature", "properties": { "ID": "41", "SOATO_U": "1841000000", "UkrName": "Новоград-Волинський", "RusName": "Новоград-Волынский", "EngName": "Novohrad-Volyns'kyi", "EngName_Tr": "Novohrad-Volyns'kyi", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 27.651960, 50.598580 ] } }
,
{ "type": "Feature", "properties": { "ID": "42", "SOATO_U": "2120450100", "UkrName": "Берегово", "RusName": "Берегово", "EngName": "Berehovo", "EngName_Tr": "Berehove", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 22.649090, 48.197180 ] } }
,
{ "type": "Feature", "properties": { "ID": "43", "SOATO_U": "2120855100", "UkrName": "Великий Березний", "RusName": "Великий Березный", "EngName": "Velykyi Bereznyi", "EngName_Tr": "Velykyi Bereznyi", "Settltype": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 22.480670, 48.902380 ] } }
,
{ "type": "Feature", "properties": { "ID": "44", "SOATO_U": "2121555401", "UkrName": "Нижнi Ворота", "RusName": "Нижние Ворота", "EngName": "Nyzhni Vorota", "EngName_Tr": "Nyzhni Vorota", "Settltype": "село", "SettlTypeR": "село", "SettlTypeE": "village", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 23.098400, 48.773400 ] } }
,
{ "type": "Feature", "properties": { "ID": "45", "SOATO_U": "2122455100", "UkrName": "Мiжгiр'я", "RusName": "Межгорье", "EngName": "Mizhhir'ya", "EngName_Tr": "Mizhhir'ya", "Settltype": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 23.521720, 48.510140 ] } }
,
{ "type": "Feature", "properties": { "ID": "46", "SOATO_U": "2122484401", "UkrName": "Нижнiй Студений", "RusName": "Нижний Студеный", "EngName": "Nyzhnii Studenyi", "EngName_Tr": "Nyzhnii Studenyi", "Settltype": "село", "SettlTypeR": "село", "SettlTypeE": "village", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 23.359690, 48.697470 ] } }
,
{ "type": "Feature", "properties": { "ID": "47", "SOATO_U": "2123650100", "UkrName": "Рахiв", "RusName": "Рахов", "EngName": "Rakhiv", "EngName_Tr": "Rakhiv", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,2,3,", "Observ": "атмосферні випадання, повітряні аерозолі, потужність експозиційної дози гамма-випромінювання", "ObservR": "", "ObservE": "" }, "geometry": { "type": "Point", "coordinates": [ 24.214420, 48.062700 ] } }
,
{ "type": "Feature", "properties": { "ID": "48", "SOATO_U": "2125350100", "UkrName": "Хуст", "RusName": "Хуст", "EngName": "Khust", "EngName_Tr": "Khust", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 23.313230, 48.182330 ] } }
,
{ "type": "Feature", "properties": { "ID": "49", "SOATO_U": "2140100000", "UkrName": "Ужгород", "RusName": "Ужгород", "EngName": "Uzhhorod", "EngName_Tr": "Uzhhorod", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 22.285290, 48.626040 ] } }
,
{ "type": "Feature", "properties": { "ID": "50", "SOATO_U": "2320355400", "UkrName": "Кирилiвка", "RusName": "Кирилловка", "EngName": "Kyrylivka", "EngName_Tr": "Kyrylivka", "Settltype": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 35.364010, 46.377060 ] } }
,
{ "type": "Feature", "properties": { "ID": "51", "SOATO_U": "2321850100", "UkrName": "Гуляйполе", "RusName": "Гуляйполе", "EngName": "Huliaipole", "EngName_Tr": "Huliaipole", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 36.266720, 47.664660 ] } }
,
{ "type": "Feature", "properties": { "ID": "52", "SOATO_U": "2323355400", "UkrName": "Пришиб", "RusName": "Пришиб", "EngName": "Pryshyb", "EngName_Tr": "Pryshyb", "Settltype": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 35.317600, 47.255570 ] } }
,
{ "type": "Feature", "properties": { "ID": "53", "SOATO_U": "2324581401", "UkrName": "Ботiєве", "RusName": "Ботиево", "EngName": "Botiieve", "EngName_Tr": "Botiieve", "Settltype": "село", "SettlTypeR": "село", "SettlTypeE": "village", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 35.836830, 46.681310 ] } }
,
{ "type": "Feature", "properties": { "ID": "54", "SOATO_U": "2340100000", "UkrName": "Запорiжжя", "RusName": "Запорожье", "EngName": "Zaporizhzhia", "EngName_Tr": "Zaporizhia", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 35.209800, 47.826120 ] } }
,
{ "type": "Feature", "properties": { "ID": "55", "SOATO_U": "2340400000", "UkrName": "Бердянськ", "RusName": "Бердянск", "EngName": "Berdians'k", "EngName_Tr": "Berdians'k", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 36.796210, 46.750510 ] } }
,
{ "type": "Feature", "properties": { "ID": "56", "SOATO_U": "2340700000", "UkrName": "Мелiтополь", "RusName": "Мелитополь", "EngName": "Melitopol'", "EngName_Tr": "Melitopol'", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 35.352800, 46.867500 ] } }
,
{ "type": "Feature", "properties": { "ID": "57", "SOATO_U": "2622050100", "UkrName": "Долина", "RusName": "Долина", "EngName": "Dolyna", "EngName_Tr": "Dolyna", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 24.000300, 48.974610 ] } }
,
{ "type": "Feature", "properties": { "ID": "58", "SOATO_U": "2640100000", "UkrName": "Iвано-Франкiвськ", "RusName": "Ивано-Франковск", "EngName": "Ivano-Frankivs'k", "EngName_Tr": "Ivano-Frankivsk", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 24.722520, 48.909010 ] } }
,
{ "type": "Feature", "properties": { "ID": "59", "SOATO_U": "2640600000", "UkrName": "Коломия", "RusName": "Коломыя", "EngName": "Kolomyia", "EngName_Tr": "Kolomyia", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 25.076930, 48.543710 ] } }
,
{ "type": "Feature", "properties": { "ID": "60", "SOATO_U": "2641000000", "UkrName": "Яремча", "RusName": "Яремча", "EngName": "Yaremcha", "EngName_Tr": "Yaremche", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 24.568670, 48.480510 ] } }
,
{ "type": "Feature", "properties": { "ID": "61", "SOATO_U": "3000000000", "UkrName": "Київ", "RusName": "Киев", "EngName": "Kyiv", "EngName_Tr": "Kyiv", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,2,3,4", "Observ": "атмосферні випадання, повітряні аерозолі, потужність експозиційної дози гамма-випромінювання, атмосферні опади", "ObservR": "атмосферные выпадения, воздушные аэрозоли, мощность экспозиционной дозы гамма-излучения, атмосферные осадки", "ObservE": "atmospheric fallout, aerosols, exposure rate of gamma radiation, atmospheric precipitation" }, "geometry": { "type": "Point", "coordinates": [ 30.438750, 50.447090 ] } }
,
{ "type": "Feature", "properties": { "ID": "62", "SOATO_U": "3220255100", "UkrName": "Баришiвка", "RusName": "Барышевка", "EngName": "Baryshivka", "EngName_Tr": "Baryshivka", "Settltype": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "ObservChar": "1,2,3,", "Observ": "атмосферні випадання, повітряні аерозолі, потужність експозиційної дози гамма-випромінювання", "ObservR": "", "ObservE": "" }, "geometry": { "type": "Point", "coordinates": [ 31.337630, 50.353740 ] } }
,
{ "type": "Feature", "properties": { "ID": "63", "SOATO_U": "3221850100", "UkrName": "Вишгород", "RusName": "Вышгород", "EngName": "Vyshhorod", "EngName_Tr": "Vyshhorod", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 30.485280, 50.582050 ] } }
,
{ "type": "Feature", "properties": { "ID": "64", "SOATO_U": "3222950100", "UkrName": "Миронiвка", "RusName": "Мироновка", "EngName": "Myronivka", "EngName_Tr": "Myronivka", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 31.020390, 49.665400 ] } }
,
{ "type": "Feature", "properties": { "ID": "65", "SOATO_U": "3223555100", "UkrName": "Полiсське", "RusName": "Полесское", "EngName": "Poliss'ke", "EngName_Tr": "Poliss'ke", "Settltype": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "ObservChar": "1,2,3,", "Observ": "атмосферні випадання, повітряні аерозолі, потужність експозиційної дози гамма-випромінювання", "ObservR": "", "ObservE": "" }, "geometry": { "type": "Point", "coordinates": [ 29.412000, 51.236800 ] } }
,
{ "type": "Feature", "properties": { "ID": "66", "SOATO_U": "3225550100", "UkrName": "Яготин", "RusName": "Яготин", "EngName": "Yahotyn", "EngName_Tr": "Yahotyn", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 31.761750, 50.278200 ] } }
,
{ "type": "Feature", "properties": { "ID": "67", "SOATO_U": "3240300000", "UkrName": "Бiла Церква", "RusName": "Белая Церковь", "EngName": "Bila Tserkva", "EngName_Tr": "Bila Tserkva", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 30.099360, 49.802660 ] } }
,
{ "type": "Feature", "properties": { "ID": "68", "SOATO_U": "3240500000", "UkrName": "Бориспiль", "RusName": "Борисполь", "EngName": "Boryspil'", "EngName_Tr": "Boryspil'", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 30.969380, 50.362580 ] } }
,
{ "type": "Feature", "properties": { "ID": "69", "SOATO_U": "3241200000", "UkrName": "Фастiв", "RusName": "Фастов", "EngName": "Fastiv", "EngName_Tr": "Fastiv", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 29.919210, 50.082940 ] } }
,
{ "type": "Feature", "properties": { "ID": "70", "SOATO_U": "3520850100", "UkrName": "Бобринець", "RusName": "Бобринец", "EngName": "Bobrynets'", "EngName_Tr": "Bobrynets'", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 32.179580, 48.064520 ] } }
,
{ "type": "Feature", "properties": { "ID": "71", "SOATO_U": "3521150100", "UkrName": "Гайворон", "RusName": "Гайворон", "EngName": "Haivoron", "EngName_Tr": "Haivoron", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 29.838460, 48.344730 ] } }
,
{ "type": "Feature", "properties": { "ID": "72", "SOATO_U": "3521750300", "UkrName": "Помiчна", "RusName": "Помошная", "EngName": "Pomichna", "EngName_Tr": "Pomichna", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 31.414940, 48.241300 ] } }
,
{ "type": "Feature", "properties": { "ID": "73", "SOATO_U": "3521950100", "UkrName": "Долинська", "RusName": "Долинская", "EngName": "Dolyns'ka", "EngName_Tr": "Dolyns'ka", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 32.781790, 48.119640 ] } }
,
{ "type": "Feature", "properties": { "ID": "74", "SOATO_U": "3523850100", "UkrName": "Новомиргород", "RusName": "Новомиргород", "EngName": "Novomyrhorod", "EngName_Tr": "Novomyrhorod", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 31.650400, 48.803770 ] } }
,
{ "type": "Feature", "properties": { "ID": "75", "SOATO_U": "3540100000", "UkrName": "Кiровоград", "RusName": "Кировоград", "EngName": "Kirovohrad", "EngName_Tr": "Kirovohrad", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 32.248160, 48.520810 ] } }
,
{ "type": "Feature", "properties": { "ID": "76", "SOATO_U": "3540600000", "UkrName": "Знам'янка", "RusName": "Знаменка", "EngName": "Znam'yanka", "EngName_Tr": "Znam'yanka", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 32.674950, 48.707830 ] } }
,
{ "type": "Feature", "properties": { "ID": "77", "SOATO_U": "3540900000", "UkrName": "Свiтловодськ", "RusName": "Светловодск", "EngName": "Svitlovods'k", "EngName_Tr": "Svitlovods'k", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 33.223790, 49.044280 ] } }
,
{ "type": "Feature", "properties": { "ID": "78", "SOATO_U": "4000000000", "UkrName": "Севастополь", "RusName": "Г.Севастополь", "EngName": "Sevastopol'", "EngName_Tr": "Sevastopol", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,2,3,4", "Observ": "атмосферні випадання, повітряні аерозолі, потужність експозиційної дози гамма-випромінювання, атмосферні опади", "ObservR": "атмосферные выпадения, воздушные аэрозоли, мощность экспозиционной дозы гамма-излучения, атмосферные осадки", "ObservE": "atmospheric fallout, aerosols, exposure rate of gamma radiation, atmospheric precipitation" }, "geometry": { "type": "Point", "coordinates": [ 33.606010, 44.503880 ] } }
,
{ "type": "Feature", "properties": { "ID": "79", "SOATO_U": "4320750100", "UkrName": "Бiлогiрськ", "RusName": "Белогорск", "EngName": "Bilohirs'k", "EngName_Tr": "Bilohirs'k", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 34.601630, 45.066280 ] } }
,
{ "type": "Feature", "properties": { "ID": "80", "SOATO_U": "4321680801", "UkrName": "Владиславiвка", "RusName": "Владиславовка", "EngName": "Vladyslavivka", "EngName_Tr": "Vladyslavivka", "Settltype": "село", "SettlTypeR": "село", "SettlTypeE": "village", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 35.381980, 45.164910 ] } }
,
{ "type": "Feature", "properties": { "ID": "81", "SOATO_U": "4322081801", "UkrName": "Клепинiне", "RusName": "Клепинино", "EngName": "Klepynine", "EngName_Tr": "Klepynine", "Settltype": "село", "SettlTypeR": "село", "SettlTypeE": "village", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 34.187830, 45.526690 ] } }
,
{ "type": "Feature", "properties": { "ID": "82", "SOATO_U": "4322382201", "UkrName": "Iшунь", "RusName": "Ишунь", "EngName": "Ishun'", "EngName_Tr": "Ishun'", "Settltype": "село", "SettlTypeR": "село", "SettlTypeE": "village", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 33.827240, 45.923980 ] } }
,
{ "type": "Feature", "properties": { "ID": "83", "SOATO_U": "4322785801", "UkrName": "Мисове", "RusName": "Мысовое", "EngName": "Mysove", "EngName_Tr": "Mysove", "Settltype": "село", "SettlTypeR": "село", "SettlTypeE": "village", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 35.838630, 45.452420 ] } }
,
{ "type": "Feature", "properties": { "ID": "84", "SOATO_U": "4323155100", "UkrName": "Нижньогiрський", "RusName": "Нижнегорский", "EngName": "Nyzhn'ohirs'kyi", "EngName_Tr": "Nyzhn'ohirs'kyi", "Settltype": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 34.740630, 45.442190 ] } }
,
{ "type": "Feature", "properties": { "ID": "85", "SOATO_U": "4323955100", "UkrName": "Роздольне", "RusName": "Раздольное", "EngName": "Rozdol'ne", "EngName_Tr": "Rozdol'ne", "Settltype": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 33.485900, 45.763390 ] } }
,
{ "type": "Feature", "properties": { "ID": "86", "SOATO_U": "4325655100", "UkrName": "Чорноморське", "RusName": "Черноморское", "EngName": "Chornomors'ke", "EngName_Tr": "Chornomors'ke", "Settltype": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 32.695060, 45.493450 ] } }
,
{ "type": "Feature", "properties": { "ID": "87", "SOATO_U": "4340100000", "UkrName": "Сiмферополь", "RusName": "Симферополь", "EngName": "Simferopol'", "EngName_Tr": "Simferopol", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 34.095410, 44.939680 ] } }
,
{ "type": "Feature", "properties": { "ID": "88", "SOATO_U": "4340300000", "UkrName": "Алушта", "RusName": "Алушта", "EngName": "Alushta", "EngName_Tr": "Alushta", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 34.404660, 44.670350 ] } }
,
{ "type": "Feature", "properties": { "ID": "89", "SOATO_U": "4340600000", "UkrName": "Джанкой", "RusName": "Джанкой", "EngName": "Dzhankoi", "EngName_Tr": "Dzhankoi", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 34.402020, 45.701220 ] } }
,
{ "type": "Feature", "properties": { "ID": "90", "SOATO_U": "4340900000", "UkrName": "Євпаторiя", "RusName": "Евпатория", "EngName": "Yevpatoriia", "EngName_Tr": "Yevpatoriia", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 33.368530, 45.189950 ] } }
,
{ "type": "Feature", "properties": { "ID": "91", "SOATO_U": "4341200000", "UkrName": "Керч", "RusName": "Керчь", "EngName": "Kerch", "EngName_Tr": "Kerch", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 36.483220, 45.354890 ] } }
,
{ "type": "Feature", "properties": { "ID": "92", "SOATO_U": "4341600000", "UkrName": "Феодосiя", "RusName": "Феодосия", "EngName": "Feodosiia", "EngName_Tr": "Feodosiia", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 35.386110, 45.056590 ] } }
,
{ "type": "Feature", "properties": { "ID": "93", "SOATO_U": "4341900000", "UkrName": "Ялта", "RusName": "Ялта", "EngName": "Yalta", "EngName_Tr": "Yalta", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 34.164870, 44.495970 ] } }
,
{ "type": "Feature", "properties": { "ID": "94", "SOATO_U": "4620350100", "UkrName": "Броди", "RusName": "Броды", "EngName": "Brody", "EngName_Tr": "Brody", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 25.170360, 50.072690 ] } }
,
{ "type": "Feature", "properties": { "ID": "95", "SOATO_U": "4622150100", "UkrName": "Кам'янка-Бузька", "RusName": "Каменка-Бугская", "EngName": "Kam'yanka-Buz'ka", "EngName_Tr": "Kam'yanka-Buz'ka", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 24.361440, 50.113060 ] } }
,
{ "type": "Feature", "properties": { "ID": "96", "SOATO_U": "4622450100", "UkrName": "Мостиська", "RusName": "Мостиска", "EngName": "Mostys'ka", "EngName_Tr": "Mostys'ka", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 23.146760, 49.807590 ] } }
,
{ "type": "Feature", "properties": { "ID": "97", "SOATO_U": "4622750400", "UkrName": "Рава-Руська", "RusName": "Рава-Русская", "EngName": "Rava-Rus'ka", "EngName_Tr": "Rava-Rus'ka", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 23.618360, 50.228260 ] } }
,
{ "type": "Feature", "properties": { "ID": "98", "SOATO_U": "4624555700", "UkrName": "Славсько", "RusName": "Славское", "EngName": "Slavs'ko", "EngName_Tr": "Slavs'ko", "Settltype": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 23.446520, 48.834810 ] } }
,
{ "type": "Feature", "properties": { "ID": "99", "SOATO_U": "4625550100", "UkrName": "Турка", "RusName": "Турка", "EngName": "Turka", "EngName_Tr": "Turka", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 23.035770, 49.158190 ] } }
,
{ "type": "Feature", "properties": { "ID": "100", "SOATO_U": "4625850100", "UkrName": "Яворiв", "RusName": "Яворов", "EngName": "Yavoriv", "EngName_Tr": "Yavoriv", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 23.391750, 49.947840 ] } }
,
{ "type": "Feature", "properties": { "ID": "101", "SOATO_U": "4640100000", "UkrName": "Львiв", "RusName": "Львов", "EngName": "L'viv", "EngName_Tr": "Lviv", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 24.000120, 49.840390 ] } }
,
{ "type": "Feature", "properties": { "ID": "102", "SOATO_U": "4640600000", "UkrName": "Дрогобич", "RusName": "Дрогобыч", "EngName": "Drohobych", "EngName_Tr": "Drohobych", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 23.521750, 49.352140 ] } }
,
{ "type": "Feature", "properties": { "ID": "103", "SOATO_U": "4641200000", "UkrName": "Стрий", "RusName": "Стрый", "EngName": "Stryi", "EngName_Tr": "Stryi", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 23.824520, 49.251870 ] } }
,
{ "type": "Feature", "properties": { "ID": "104", "SOATO_U": "4820650100", "UkrName": "Баштанка", "RusName": "Баштанка", "EngName": "Bashtanka", "EngName_Tr": "Bashtanka", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 32.421290, 47.397440 ] } }
,
{ "type": "Feature", "properties": { "ID": "105", "SOATO_U": "4840100000", "UkrName": "Миколаїв", "RusName": "Николаев", "EngName": "Mykolaiv", "EngName_Tr": "Mykolaiv", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 32.004050, 46.961530 ] } }
,
{ "type": "Feature", "properties": { "ID": "106", "SOATO_U": "4840200000", "UkrName": "Вознесенськ", "RusName": "Вознесенск", "EngName": "Voznesens'k", "EngName_Tr": "Voznesens'k", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 31.332380, 47.565980 ] } }
,
{ "type": "Feature", "properties": { "ID": "107", "SOATO_U": "4840300000", "UkrName": "Очакiв", "RusName": "Очаков", "EngName": "Ochakiv", "EngName_Tr": "Ochakiv", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 31.554380, 46.605270 ] } }
,
{ "type": "Feature", "properties": { "ID": "108", "SOATO_U": "5121450100", "UkrName": "Болград", "RusName": "Болград", "EngName": "Bolhrad", "EngName_Tr": "Bolhrad", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 28.635220, 45.676610 ] } }
,
{ "type": "Feature", "properties": { "ID": "109", "SOATO_U": "5122350300", "UkrName": "Вилкове", "RusName": "Вилково", "EngName": "Vylkove", "EngName_Tr": "Vylkove", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 29.580470, 45.398460 ] } }
,
{ "type": "Feature", "properties": { "ID": "110", "SOATO_U": "5122785501", "UkrName": "Сербка", "RusName": "Сербка", "EngName": "Serbka", "EngName_Tr": "Serbka", "Settltype": "село", "SettlTypeR": "село", "SettlTypeE": "village", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 30.769290, 47.002610 ] } }
,
{ "type": "Feature", "properties": { "ID": "111", "SOATO_U": "5123355100", "UkrName": "Любашiвка", "RusName": "Любашевка", "EngName": "Liubashivka", "EngName_Tr": "Liubashivka", "Settltype": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 30.254090, 47.825030 ] } }
,
{ "type": "Feature", "properties": { "ID": "112", "SOATO_U": "5123950100", "UkrName": "Роздiльна", "RusName": "Раздельная", "EngName": "Rozdil'na", "EngName_Tr": "Rozdil'na", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 30.079090, 46.843490 ] } }
,
{ "type": "Feature", "properties": { "ID": "113", "SOATO_U": "5124555100", "UkrName": "Сарата", "RusName": "Сарата", "EngName": "Sarata", "EngName_Tr": "Sarata", "Settltype": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 29.655520, 46.036780 ] } }
,
{ "type": "Feature", "properties": { "ID": "114", "SOATO_U": "5125255400", "UkrName": "Затишшя", "RusName": "Затишье", "EngName": "Zatyshshia", "EngName_Tr": "Zatyshshia", "Settltype": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 29.870570, 47.337810 ] } }
,
{ "type": "Feature", "properties": { "ID": "115", "SOATO_U": "5140100000", "UkrName": "Одеса", "RusName": "Одесса", "EngName": "Odesa", "EngName_Tr": "Odesa", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,2,3,4", "Observ": "атмосферні випадання, повітряні аерозолі, потужність експозиційної дози гамма-випромінювання, атмосферні опади", "ObservR": "атмосферные выпадения, воздушные аэрозоли, мощность экспозиционной дозы гамма-излучения, атмосферные осадки", "ObservE": "atmospheric fallout, aerosols, exposure rate of gamma radiation, atmospheric precipitation" }, "geometry": { "type": "Point", "coordinates": [ 30.701380, 46.426860 ] } }
,
{ "type": "Feature", "properties": { "ID": "116", "SOATO_U": "5140300000", "UkrName": "Бiлгород-Днiстровський", "RusName": "Белгород-Днестровский", "EngName": "Bilhorod-Dnistrovs'kyi", "EngName_Tr": "Bilhorod-Dnistrovs'kyi", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 30.331550, 46.191320 ] } }
,
{ "type": "Feature", "properties": { "ID": "117", "SOATO_U": "5140600000", "UkrName": "Iзмаїл", "RusName": "Измаил", "EngName": "Izmail", "EngName_Tr": "Izmail", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 28.822220, 45.368920 ] } }
,
{ "type": "Feature", "properties": { "ID": "118", "SOATO_U": "5140800000", "UkrName": "Iллiчiвськ", "RusName": "Ильичевск", "EngName": "Illichivs'k", "EngName_Tr": "Illichivs'k", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 30.667030, 46.302750 ] } }
,
{ "type": "Feature", "properties": { "ID": "119", "SOATO_U": "5320450100", "UkrName": "Гадяч", "RusName": "Гадяч", "EngName": "Hadiach", "EngName_Tr": "Hadiach", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 33.996210, 50.369290 ] } }
,
{ "type": "Feature", "properties": { "ID": "120", "SOATO_U": "5321850100", "UkrName": "Кобеляки", "RusName": "Кобеляки", "EngName": "Kobeliaky", "EngName_Tr": "Kobeliaky", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 34.219870, 49.152200 ] } }
,
{ "type": "Feature", "properties": { "ID": "121", "SOATO_U": "5324581201", "UkrName": "Веселий Подiл", "RusName": "Веселый Подол", "EngName": "Veselyi Podil", "EngName_Tr": "Veselyi Podil", "Settltype": "село", "SettlTypeR": "село", "SettlTypeE": "village", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 33.271520, 49.605690 ] } }
,
{ "type": "Feature", "properties": { "ID": "122", "SOATO_U": "5340100000", "UkrName": "Полтава", "RusName": "Полтава", "EngName": "Poltava", "EngName_Tr": "Poltava", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 34.602030, 49.600320 ] } }
,
{ "type": "Feature", "properties": { "ID": "123", "SOATO_U": "5340400000", "UkrName": "Кременчук", "RusName": "Кременчуг", "EngName": "Kremenchuk", "EngName_Tr": "Kremenchuk", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 33.425810, 49.103310 ] } }
,
{ "type": "Feature", "properties": { "ID": "124", "SOATO_U": "5340700000", "UkrName": "Лубни", "RusName": "Лубны", "EngName": "Lubny", "EngName_Tr": "Lubny", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 33.023290, 50.020080 ] } }
,
{ "type": "Feature", "properties": { "ID": "125", "SOATO_U": "5625082602", "UkrName": "Дубно", "RusName": "Дубно", "EngName": "Dubno", "EngName_Tr": "Dubno", "Settltype": "село", "SettlTypeR": "село", "SettlTypeE": "village", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 27.510480, 51.521610 ] } }
,
{ "type": "Feature", "properties": { "ID": "126", "SOATO_U": "5625450100", "UkrName": "Сарни", "RusName": "Сарны", "EngName": "Sarny", "EngName_Tr": "Sarny", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 26.620180, 51.323770 ] } }
,
{ "type": "Feature", "properties": { "ID": "127", "SOATO_U": "5640100000", "UkrName": "Рiвне", "RusName": "Ровно", "EngName": "Rivne", "EngName_Tr": "Rivne", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 26.259440, 50.633160 ] } }
,
{ "type": "Feature", "properties": { "ID": "128", "SOATO_U": "5925650300", "UkrName": "Дружба", "RusName": "Дружба", "EngName": "Druzhba", "EngName_Tr": "Druzhba", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 33.947850, 52.050800 ] } }
,
{ "type": "Feature", "properties": { "ID": "129", "SOATO_U": "5940100000", "UkrName": "Суми", "RusName": "Сумы", "EngName": "Sumy", "EngName_Tr": "Sumy", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 34.804230, 50.914490 ] } }
,
{ "type": "Feature", "properties": { "ID": "130", "SOATO_U": "5940300000", "UkrName": "Глухiв", "RusName": "Глухов", "EngName": "Hlukhiv", "EngName_Tr": "Hlukhiv", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 33.935100, 51.680650 ] } }
,
{ "type": "Feature", "properties": { "ID": "131", "SOATO_U": "5940400000", "UkrName": "Конотоп", "RusName": "Конотоп", "EngName": "Konotop", "EngName_Tr": "Konotop", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 33.231220, 51.238500 ] } }
,
{ "type": "Feature", "properties": { "ID": "132", "SOATO_U": "5940500000", "UkrName": "Лебедин", "RusName": "Лебедин", "EngName": "Lebedyn", "EngName_Tr": "Lebedyn", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 34.491680, 50.584750 ] } }
,
{ "type": "Feature", "properties": { "ID": "133", "SOATO_U": "5940700000", "UkrName": "Ромни", "RusName": "Ромны", "EngName": "Romny", "EngName_Tr": "Romny", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 33.492960, 50.750130 ] } }
,
{ "type": "Feature", "properties": { "ID": "134", "SOATO_U": "6120450100", "UkrName": "Бережани", "RusName": "Бережаны", "EngName": "Berezhany", "EngName_Tr": "Berezhany", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 24.928440, 49.447020 ] } }
,
{ "type": "Feature", "properties": { "ID": "135", "SOATO_U": "6123450100", "UkrName": "Кременець", "RusName": "Кременец", "EngName": "Kremenets'", "EngName_Tr": "Kremenets'", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 25.726290, 50.103340 ] } }
,
{ "type": "Feature", "properties": { "ID": "136", "SOATO_U": "6125550100", "UkrName": "Чорткiв", "RusName": "Чортков", "EngName": "Chortkiv", "EngName_Tr": "Chortkiv", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 25.804570, 49.019150 ] } }
,
{ "type": "Feature", "properties": { "ID": "137", "SOATO_U": "6140100000", "UkrName": "Тернопiль", "RusName": "Тернополь", "EngName": "Ternopil'", "EngName_Tr": "Ternopil", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 25.618270, 49.553050 ] } }
,
{ "type": "Feature", "properties": { "ID": "138", "SOATO_U": "6320850100", "UkrName": "Богодухiв", "RusName": "Богодухов", "EngName": "Bohodukhiv", "EngName_Tr": "Bohodukhiv", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 35.568120, 50.165530 ] } }
,
{ "type": "Feature", "properties": { "ID": "139", "SOATO_U": "6321455100", "UkrName": "Великий Бурлук", "RusName": "Великий Бурлук", "EngName": "Velykyi Burluk", "EngName_Tr": "Velykyi Burluk", "Settltype": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 37.363600, 50.044280 ] } }
,
{ "type": "Feature", "properties": { "ID": "140", "SOATO_U": "6322655100", "UkrName": "Золочiв", "RusName": "Золочев", "EngName": "Zolochiv", "EngName_Tr": "Zolochiv", "Settltype": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 35.959150, 50.283640 ] } }
,
{ "type": "Feature", "properties": { "ID": "141", "SOATO_U": "6322888001", "UkrName": "Червоний Оскiл", "RusName": "Червоный Оскол", "EngName": "Chervonyi Oskil", "EngName_Tr": "Chervonyi Oskil", "Settltype": "село", "SettlTypeR": "село", "SettlTypeE": "village", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 37.425710, 49.181750 ] } }
,
{ "type": "Feature", "properties": { "ID": "142", "SOATO_U": "6323255100", "UkrName": "Коломак", "RusName": "Коломак", "EngName": "Kolomak", "EngName_Tr": "Kolomak", "Settltype": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 35.313610, 49.834800 ] } }
,
{ "type": "Feature", "properties": { "ID": "143", "SOATO_U": "6323350100", "UkrName": "Красноград", "RusName": "Красноград", "EngName": "Krasnohrad", "EngName_Tr": "Krasnohrad", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 35.445650, 49.371100 ] } }
,
{ "type": "Feature", "properties": { "ID": "144", "SOATO_U": "6324655100", "UkrName": "Печенiги", "RusName": "Печенеги", "EngName": "Pechenihy", "EngName_Tr": "Pechenihy", "Settltype": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 36.931810, 49.867510 ] } }
,
{ "type": "Feature", "properties": { "ID": "145", "SOATO_U": "6340100000", "UkrName": "Харкiв", "RusName": "Харьков", "EngName": "Kharkiv", "EngName_Tr": "Kharkiv", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 36.289160, 49.990930 ] } }
,
{ "type": "Feature", "properties": { "ID": "146", "SOATO_U": "6340400000", "UkrName": "Iзюм", "RusName": "Изюм", "EngName": "Izium", "EngName_Tr": "Izium", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 37.273080, 49.194710 ] } }
,
{ "type": "Feature", "properties": { "ID": "147", "SOATO_U": "6340700000", "UkrName": "Куп'янськ", "RusName": "Купянск", "EngName": "Kup'yans'k", "EngName_Tr": "Kup'yans'k", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 37.594320, 49.702990 ] } }
,
{ "type": "Feature", "properties": { "ID": "148", "SOATO_U": "6341000000", "UkrName": "Лозова", "RusName": "Лозовая", "EngName": "Lozova", "EngName_Tr": "Lozova", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 36.312520, 48.890090 ] } }
,
{ "type": "Feature", "properties": { "ID": "149", "SOATO_U": "6520955100", "UkrName": "Велика Олександрiвка", "RusName": "Великая Александровка", "EngName": "Velyka Oleksandrivka", "EngName_Tr": "Velyka Oleksandrivka", "Settltype": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 33.317490, 47.317920 ] } }
,
{ "type": "Feature", "properties": { "ID": "150", "SOATO_U": "6522150100", "UkrName": "Генiчеськ", "RusName": "Геническ", "EngName": "Heniches'k", "EngName_Tr": "Heniches'k", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 34.805130, 46.169370 ] } }
,
{ "type": "Feature", "properties": { "ID": "151", "SOATO_U": "6522380501", "UkrName": "Бехтери", "RusName": "Бехтеры", "EngName": "Bekhtery", "EngName_Tr": "Bekhtery", "Settltype": "село", "SettlTypeR": "село", "SettlTypeE": "village", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 32.315890, 46.246530 ] } }
,
{ "type": "Feature", "properties": { "ID": "152", "SOATO_U": "6523286601", "UkrName": "Хорли", "RusName": "Хорлы", "EngName": "Khorly", "EngName_Tr": "Khorly", "Settltype": "село", "SettlTypeR": "село", "SettlTypeE": "village", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 33.299180, 46.079010 ] } }
,
{ "type": "Feature", "properties": { "ID": "153", "SOATO_U": "6523855100", "UkrName": "Нижнi Сiрогози", "RusName": "Нижние Серогозы", "EngName": "Nyzhni Sirohozy", "EngName_Tr": "Nyzhni Sirohozy", "Settltype": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 34.369700, 46.841530 ] } }
,
{ "type": "Feature", "properties": { "ID": "154", "SOATO_U": "6525455300", "UkrName": "Асканiя-Нова", "RusName": "Аскания-Нова", "EngName": "Askaniia-Nova", "EngName_Tr": "Askaniia-Nova", "Settltype": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 33.873650, 46.459330 ] } }
,
{ "type": "Feature", "properties": { "ID": "155", "SOATO_U": "6540100000", "UkrName": "Херсон", "RusName": "Херсон", "EngName": "Kherson", "EngName_Tr": "Kherson", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 32.649240, 46.662860 ] } }
,
{ "type": "Feature", "properties": { "ID": "156", "SOATO_U": "6540700000", "UkrName": "Нова Каховка", "RusName": "Новая Каховка", "EngName": "Nova Kakhovka", "EngName_Tr": "Nova Kakhovka", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 33.331190, 46.744040 ] } }
,
{ "type": "Feature", "properties": { "ID": "157", "SOATO_U": "6820355600", "UkrName": "Ямпiль", "RusName": "Ямполь", "EngName": "Yampil'", "EngName_Tr": "Yampil'", "Settltype": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 26.238710, 49.952830 ] } }
,
{ "type": "Feature", "properties": { "ID": "158", "SOATO_U": "6823355100", "UkrName": "Нова Ушиця", "RusName": "Новая Ушица", "EngName": "Nova Ushytsia", "EngName_Tr": "Nova Ushytsia", "Settltype": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 27.290670, 48.835110 ] } }
,
{ "type": "Feature", "properties": { "ID": "159", "SOATO_U": "6840100000", "UkrName": "Хмельницький", "RusName": "Хмельницкий", "EngName": "Khmel'nyts'kyi", "EngName_Tr": "Khmelnytskyi", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 26.977800, 49.427290 ] } }
,
{ "type": "Feature", "properties": { "ID": "160", "SOATO_U": "6840400000", "UkrName": "Кам'янець-Подiльський", "RusName": "Каменец-Подольский", "EngName": "Kam'yanets'-Podil's'kyi", "EngName_Tr": "Kam'yanets'-Podil's'kyi", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 26.595660, 48.684810 ] } }
,
{ "type": "Feature", "properties": { "ID": "161", "SOATO_U": "6840700000", "UkrName": "Шепетiвка", "RusName": "Шепетовка", "EngName": "Shepetivka", "EngName_Tr": "Shepetivka", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,2,3,", "Observ": "атмосферні випадання, повітряні аерозолі, потужність експозиційної дози гамма-випромінювання", "ObservR": "", "ObservE": "" }, "geometry": { "type": "Point", "coordinates": [ 27.077770, 50.181290 ] } }
,
{ "type": "Feature", "properties": { "ID": "162", "SOATO_U": "7120950100", "UkrName": "Жашкiв", "RusName": "Жашков", "EngName": "Zhashkiv", "EngName_Tr": "Zhashkiv", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 30.109820, 49.244320 ] } }
,
{ "type": "Feature", "properties": { "ID": "163", "SOATO_U": "7121250100", "UkrName": "Звенигородка", "RusName": "Звенигородка", "EngName": "Zvenyhorodka", "EngName_Tr": "Zvenyhorodka", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 30.969850, 49.080800 ] } }
,
{ "type": "Feature", "properties": { "ID": "164", "SOATO_U": "7125450100", "UkrName": "Чигирин", "RusName": "Чигирин", "EngName": "Chyhyryn", "EngName_Tr": "Chyhyryn", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 32.660860, 49.085740 ] } }
,
{ "type": "Feature", "properties": { "ID": "165", "SOATO_U": "7140100000", "UkrName": "Черкаси", "RusName": "Черкассы", "EngName": "Cherkasy", "EngName_Tr": "Cherkasy", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 32.050520, 49.428480 ] } }
,
{ "type": "Feature", "properties": { "ID": "166", "SOATO_U": "7140300000", "UkrName": "Канiв", "RusName": "Канев", "EngName": "Kaniv", "EngName_Tr": "Kaniv", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 31.454520, 49.751050 ] } }
,
{ "type": "Feature", "properties": { "ID": "167", "SOATO_U": "7140400000", "UkrName": "Золотоноша", "RusName": "Золотоноша", "EngName": "Zolotonosha", "EngName_Tr": "Zolotonosha", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 32.031000, 49.679680 ] } }
,
{ "type": "Feature", "properties": { "ID": "168", "SOATO_U": "7140500000", "UkrName": "Смiла", "RusName": "Смела", "EngName": "Smila", "EngName_Tr": "Smila", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 31.883060, 49.218390 ] } }
,
{ "type": "Feature", "properties": { "ID": "169", "SOATO_U": "7140800000", "UkrName": "Умань", "RusName": "Умань", "EngName": "Uman'", "EngName_Tr": "Uman'", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 30.213180, 48.757530 ] } }
,
{ "type": "Feature", "properties": { "ID": "170", "SOATO_U": "7422050400", "UkrName": "Остер", "RusName": "Остер", "EngName": "Oster", "EngName_Tr": "Oster", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 30.902060, 50.953650 ] } }
,
{ "type": "Feature", "properties": { "ID": "171", "SOATO_U": "7422286001", "UkrName": "Покошичi", "RusName": "Покошичи", "EngName": "Pokoshychi", "EngName_Tr": "Pokoshychi", "Settltype": "село", "SettlTypeR": "село", "SettlTypeE": "village", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 32.951800, 51.778730 ] } }
,
{ "type": "Feature", "properties": { "ID": "172", "SOATO_U": "7424750100", "UkrName": "Семенiвка", "RusName": "Семеновка", "EngName": "Semenivka", "EngName_Tr": "Semenivka", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 32.626100, 52.182320 ] } }
,
{ "type": "Feature", "properties": { "ID": "173", "SOATO_U": "7425850100", "UkrName": "Щорс", "RusName": "Щорс", "EngName": "Shchors", "EngName_Tr": "Shchors", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,2,3,", "Observ": "атмосферні випадання, повітряні аерозолі, потужність експозиційної дози гамма-випромінювання", "ObservR": "", "ObservE": "" }, "geometry": { "type": "Point", "coordinates": [ 31.961030, 51.829430 ] } }
,
{ "type": "Feature", "properties": { "ID": "174", "SOATO_U": "7440100000", "UkrName": "Чернiгiв", "RusName": "Чернигов", "EngName": "Chernihiv", "EngName_Tr": "Chernihiv", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 31.332290, 51.513940 ] } }
,
{ "type": "Feature", "properties": { "ID": "175", "SOATO_U": "7440400000", "UkrName": "Нiжин", "RusName": "Нежин", "EngName": "Nizhyn", "EngName_Tr": "Nizhyn", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 31.886450, 51.043330 ] } }
,
{ "type": "Feature", "properties": { "ID": "176", "SOATO_U": "7440700000", "UkrName": "Прилуки", "RusName": "Прилуки", "EngName": "Pryluky", "EngName_Tr": "Pryluky", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 32.405480, 50.600270 ] } }
,
{ "type": "Feature", "properties": { "ID": "177", "SOATO_U": "7723584501", "UkrName": "Селятин", "RusName": "Селятин", "EngName": "Seliatyn", "EngName_Tr": "Seliatyn", "Settltype": "село", "SettlTypeR": "село", "SettlTypeE": "village", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 25.206090, 47.863990 ] } }
,
{ "type": "Feature", "properties": { "ID": "178", "SOATO_U": "7724050300", "UkrName": "Новоднiстровськ", "RusName": "Новоднестровск", "EngName": "Novodnistrovs'k", "EngName_Tr": "Novodnistrovs'k", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 27.454300, 48.570750 ] } }
,
{ "type": "Feature", "properties": { "ID": "179", "SOATO_U": "7740100000", "UkrName": "Чернiвцi", "RusName": "Черновцы", "EngName": "Chernivtsi", "EngName_Tr": "Chernivtsi", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 25.887900, 48.299080 ] } }
,
{ "type": "Feature", "properties": { "ID": "180", "SOATO_U": "2340100000", "UkrName": "Запорiжжя", "RusName": "Запорожье", "EngName": "Zaporizhzhia", "EngName_Tr": "Zaporizhia", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 35.209800, 47.826120 ] } }
,
{ "type": "Feature", "properties": { "ID": "181", "SOATO_U": "3000000000", "UkrName": "Київ", "RusName": "Киев", "EngName": "Kyiv", "EngName_Tr": "Kyiv", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 30.438750, 50.447090 ] } }
,
{ "type": "Feature", "properties": { "ID": "182", "SOATO_U": "4640100000", "UkrName": "Львiв", "RusName": "Львов", "EngName": "L'viv", "EngName_Tr": "Lviv", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 24.000120, 49.840390 ] } }
,
{ "type": "Feature", "properties": { "ID": "183", "SOATO_U": "1840700000", "UkrName": "Коростень", "RusName": "Коростень", "EngName": "Korosten'", "EngName_Tr": "Korosten'", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,2,3,", "Observ": "атмосферні випадання, повітряні аерозолі, потужність експозиційної дози гамма-випромінювання", "ObservR": "", "ObservE": "" }, "geometry": { "type": "Point", "coordinates": [ 28.659270, 50.957620 ] } }
,
{ "type": "Feature", "properties": { "ID": "184", "SOATO_U": "4840400000", "UkrName": "Первомайськ", "RusName": "Первомайск", "EngName": "Pervomais'k", "EngName_Tr": "Pervomais'k", "Settltype": "місто", "SettlTypeR": "город", "SettlTypeE": "city", "ObservChar": "1,3,", "Observ": "атмосферні випадання, потужність експозиційної дози гамма-випромінювання", "ObservR": "атмосферные выпадения, мощность экспозиционной дозы гамма-излучения", "ObservE": "atmospheric fallout, exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 30.873530, 48.048030 ] } }
,
{ "type": "Feature", "properties": { "ID": "185", "SOATO_U": "6321755600", "UkrName": "Комсомольське", "RusName": "Комсомольское", "EngName": "Komsomol's'ke", "EngName_Tr": "Komsomol's'ke", "Settltype": "смт.", "SettlTypeR": "пгт.", "SettlTypeE": "town", "ObservChar": "3,", "Observ": "потужність експозиційної дози гамма-випромінювання", "ObservR": "мощность экспозиционной дозы гамма-излучения", "ObservE": "exposure rate of gamma radiation" }, "geometry": { "type": "Point", "coordinates": [ 36.505650, 49.599890 ] } }

]
}
